
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'de' | 'sq';

interface Translations {
  [key: string]: {
    [key in Language]: string;
  };
}

const translations: Translations = {
  // --- COMMON ---
  // --- Oeffentliche Seiten: bis hierher fest verdrahtet und damit von der
  // Sprachwahl unberuehrt. Die Texte lagen in drei Sprachen gemischt vor.
  'hero.donate.hint': { en: 'Instant & secure donation', de: 'Sofort und sicher spenden', sq: 'Dhurim i menjëhershëm dhe i sigurt' },
  'hero.stats.members': { en: 'Members', de: 'Mitglieder', sq: 'Anëtarë' },
  'hero.stats.diaspora': { en: 'Active in the diaspora', de: 'Aktiv in der Diaspora', sq: 'Aktivë në diasporë' },
  'hero.mission.badge': { en: 'Our Mission', de: 'Unser Auftrag', sq: 'Misioni Ynë' },
  'hero.community.badge': { en: 'Our Community', de: 'Unsere Gemeinschaft', sq: 'Komuniteti ynë' },
  'hero.qr.title': { en: 'Scan & Pay', de: 'Scannen & bezahlen', sq: 'Skano & Paguaj' },
  'hero.qr.desc': { en: 'Use your TWINT app to scan the code.', de: 'Scannen Sie den Code mit Ihrer TWINT-App.', sq: 'Përdorni aplikacionin TWINT për të skanuar kodin.' },

  'app.maintenance.title': { en: 'Under maintenance', de: 'Wartungsarbeiten', sq: 'Në mirëmbajtje' },
  'app.maintenance.desc': { en: 'The system is being updated. Please come back later.', de: 'Das System wird gerade aktualisiert. Bitte später erneut versuchen.', sq: 'Përmirësim i sistemit në rrjedhë e sipër. Ju lutem kthehuni më vonë.' },
  'app.connecting': { en: 'Connecting...', de: 'Verbindung wird hergestellt...', sq: 'Duke u lidhur...' },
  'nav.about': { en: 'About us', de: 'Über uns', sq: 'Rreth Nesh' },
  'nav.home': { en: 'Home', de: 'Startseite', sq: 'Ballina' },
  'nav.membership': { en: 'Membership', de: 'Mitgliedschaft', sq: 'Anëtarësimi' },
  'nav.signout': { en: 'Sign out', de: 'Abmelden', sq: 'Dilni' },
  'footer.contact': { en: 'Contact', de: 'Kontakt', sq: 'Kontakt' },
  'footer.links': { en: 'Links', de: 'Links', sq: 'Linke' },

  'events.reg.done': { en: 'You have requested registration for {event}. You will be notified once it is approved.', de: 'Sie haben sich für {event} angemeldet. Sie werden benachrichtigt, sobald die Anmeldung bestätigt ist.', sq: 'Ju keni kërkuar regjistrimin për {event}. Ju do të njoftoheni kur të miratohet.' },
  'events.reg.close': { en: 'Close', de: 'Schliessen', sq: 'Mbyll' },
  'events.reg.intro': { en: 'Please enter your details to register.', de: 'Bitte geben Sie Ihre Angaben für die Anmeldung ein.', sq: 'Ju lutem shënoni detajet tuaja për regjistrim.' },
  'events.reg.name': { en: 'Full name', de: 'Vollständiger Name', sq: 'Emri i Plotë' },
  'events.reg.email': { en: 'Email address', de: 'E-Mail-Adresse', sq: 'Email Adresa' },
  'events.reg.phone': { en: 'Phone (optional)', de: 'Telefon (optional)', sq: 'Telefoni (Opsionale)' },

  'about.stats.members': { en: 'Active Members', de: 'Aktive Mitglieder', sq: 'Anëtarë Aktiv' },
  'about.stats.neighborhoods': { en: 'Neighborhoods', de: 'Nachbarschaften', sq: 'Lagje' },
  'about.map.center_desc': { en: 'The heart of our global network.', de: 'Der Mittelpunkt unseres weltweiten Netzwerks.', sq: 'Pika qendrore e rrjetit tonë global.' },

  'news.badge': { en: 'Latest', de: 'Aktuelles', sq: 'Aktualiteti' },
  'news.subtitle': { en: 'News from Koretin and the diaspora.', de: 'Neues aus Koretin und der Diaspora.', sq: 'Të rejat nga Koretini dhe diaspora.' },
  'news.empty': { en: 'No news published at the moment.', de: 'Zurzeit sind keine Beiträge veröffentlicht.', sq: 'Nuk ka lajme të publikuara aktualisht.' },
  'news.no_content': { en: 'No content available.', de: 'Kein Inhalt vorhanden.', sq: 'Nuk ka përmbajtje.' },

  'nb.title': { en: 'Neighborhoods', de: 'Nachbarschaften', sq: 'Lagjet' },
  'nb.subtitle': { en: 'Discover and join local humanitarian groups.', de: 'Entdecken Sie die Nachbarschaften und schliessen Sie sich an.', sq: 'Zbuloni dhe bashkohuni me grupet humanitare lokale.' },
  'nb.loading': { en: 'Loading neighborhoods...', de: 'Nachbarschaften werden geladen...', sq: 'Duke ngarkuar lagjet...' },
  'nb.empty_title': { en: 'No neighborhoods yet', de: 'Noch keine Nachbarschaften', sq: 'Ende asnjë lagje' },
  'nb.empty_desc': { en: 'They will appear here as soon as they are set up.', de: 'Sobald Nachbarschaften angelegt sind, erscheinen sie hier.', sq: 'Sapo të krijohen, do të shfaqen këtu.' },
  'nb.members': { en: 'Members', de: 'Mitglieder', sq: 'Anëtarë' },
  'nb.last_activity': { en: 'Last Activity', de: 'Letzte Aktivität', sq: 'Aktiviteti i fundit' },
  'nb.search': { en: 'Search by name or town...', de: 'Nach Name oder Ort suchen...', sq: 'Kërko sipas emrit ose vendit...' },

  'cookie.body': { en: 'We use cookies to improve your experience. By continuing, you accept our terms.', de: 'Wir verwenden Cookies, um Ihr Erlebnis zu verbessern. Wenn Sie fortfahren, akzeptieren Sie unsere Bedingungen.', sq: 'Ne përdorim cookies për të përmirësuar përvojën tuaj. Duke vazhduar, ju pranoni kushtet tona.' },
  'cookie.more': { en: 'Read more at', de: 'Mehr dazu unter', sq: 'Lexoni më shumë te' },
  'cookie.accept': { en: 'Accept', de: 'Annehmen', sq: 'Pranoj' },
  'cookie.decline': { en: 'Decline', de: 'Ablehnen', sq: 'Refuzoj' },
  'cookie.title': { en: 'Privacy & Cookies', de: 'Datenschutz & Cookies', sq: 'Privatësia & Cookies' },
  'cookie.privacy_link': { en: 'Privacy', de: 'Datenschutz', sq: 'Privatësia' },

  'legal.empty': { en: 'No content has been published yet.', de: 'Es wurde noch kein Inhalt veröffentlicht.', sq: 'Ende nuk është publikuar asnjë përmbajtje.' },

  'live.header.badge': { en: 'Koretini Live', de: 'Koretini Live', sq: 'Koretini Live' },
  'live.empty': { en: 'No events scheduled yet.', de: 'Zurzeit sind keine Veranstaltungen geplant.', sq: 'Ende nuk ka ngjarje të planifikuara.' },
  'live.contact': { en: 'Contact us', de: 'Kontaktieren Sie uns', sq: 'Na kontaktoni' },

  'common.yes': { en: 'Yes', de: 'Ja', sq: 'Po' },
  'common.no': { en: 'No', de: 'Nein', sq: 'Jo' },
  'common.or': { en: 'OR', de: 'ODER', sq: 'OSE' },
  'common.back': { en: 'Back', de: 'Zurück', sq: 'Kthehu' },
  'common.next': { en: 'Next', de: 'Weiter', sq: 'Vazhdo' },
  'common.finish': { en: 'Finish', de: 'Abschließen', sq: 'Përfundo' },
  'common.loading': { en: 'Loading...', de: 'Laden...', sq: 'Duke ngarkuar...' },
  'common.error': { en: 'Error', de: 'Fehler', sq: 'Gabim' },
  'common.success': { en: 'Success', de: 'Erfolg', sq: 'Sukses' },
  'common.select': { en: 'Select...', de: 'Wählen...', sq: 'Zgjidh...' },
  'common.actions': { en: 'Actions', de: 'Aktionen', sq: 'Veprimet' },
  'common.search': { en: 'Search...', de: 'Suchen...', sq: 'Kërko...' },
  'common.cancel': { en: 'Cancel', de: 'Abbrechen', sq: 'Anulo' },
  'common.delete': { en: 'Delete', de: 'Löschen', sq: 'Fshij' },
  'common.edit': { en: 'Edit', de: 'Bearbeiten', sq: 'Ndrysho' },
  'common.save_changes': { en: 'Save Changes', de: 'Änderungen speichern', sq: 'Ruaj ndryshimet' },

  // --- NAVIGATION ---
  'nav.discover': { en: 'Discover', de: 'Entdecken', sq: 'Zbulo' },
  'nav.news.title': { en: 'Latest News', de: 'Aktuelle Nachrichten', sq: 'Të Rejat' },
  'nav.news.desc': { en: 'Updates from Koretin and the Diaspora.', de: 'Updates aus Koretin und der Diaspora.', sq: 'Lajme nga Koretini dhe Diaspora.' },
  'nav.events.title': { en: 'Events & Live', de: 'Events & Live', sq: 'Ngjarjet & Live' },
  'nav.events.desc': { en: 'Join community gatherings and projects.', de: 'Nimm an Treffen und Projekten teil.', sq: 'Bashkohuni në tubime dhe projekte.' },
  'nav.live': { en: 'Koretini Live', de: 'Koretini Live', sq: 'Koretini Live' },
  'nav.dashboard': { en: 'Dashboard', de: 'Dashboard', sq: 'Paneli' },
  'nav.admin': { en: 'Admin', de: 'Admin', sq: 'Admin' },
  'nav.logout': { en: 'Logout', de: 'Abmelden', sq: 'Dilni' },
  'nav.login': { en: 'Login', de: 'Anmelden', sq: 'Hyrja' },
  'nav.join': { en: 'Join', de: 'Beitreten', sq: 'Bashkohu' },
  'nav.adminAccess': { en: 'Admin Access', de: 'Admin Zugang', sq: 'Qasja Admin' },

  // --- HERO & LANDING ---
  'hero.badge': { en: 'Humanitarian Network', de: 'Humanitäres Netzwerk', sq: 'Rrjeti Humanitar' },
  'hero.title': { en: 'Together for our hometown.', de: 'Gemeinsam für unsere Heimat.', sq: 'Bashkë për vendlindjen tonë.' },
  'hero.subtitle': { en: 'Connecting the diaspora with local initiatives to build a better future.', de: 'Wir verbinden die Diaspora mit lokalen Initiativen für eine bessere Zukunft.', sq: 'Lidhja e diasporës me iniciativat lokale për të ndërtuar një të ardhme më të mirë.' },
  'hero.cta.register': { en: 'Join Now', de: 'Jetzt beitreten', sq: 'Regjistrohu Tani' },
  'hero.cta.login': { en: 'Login', de: 'Anmelden', sq: 'Kyçuni' },

  // --- SOCIAL AI ---
  'social.studio': { en: 'AI Studio', de: 'KI Studio', sq: 'Studio AI' },
  'social.config': { en: 'Configuration', de: 'Konfiguration', sq: 'Konfigurimi' },
  'social.topic.label': { en: 'Topic or Event', de: 'Thema oder Ereignis', sq: 'Tema apo Ngjarja' },
  'social.topic.placeholder': { en: 'e.g. Humanitarian dinner for the school...', de: 'z.B. Humanitäres Abendessen für die Schule...', sq: 'Psh: Darkë humanitare për shkollën...' },
  'social.tone.label': { en: 'Tone of Voice', de: 'Schreibstil', sq: 'Toni i shkrimit' },
  'social.lang.label': { en: 'Content Language', de: 'Inhaltssprache', sq: 'Gjuha e përmbajtjes' },
  'social.generate': { en: 'Generate Text with AI', de: 'Text mit KI generieren', sq: 'Gjenero tekstin me AI' },
  'social.analyze': { en: 'Analyze Photo & Write', de: 'Foto analysieren & schreiben', sq: 'Analizo foton & shkruaj' },
  'social.publish': { en: 'Publish Now', de: 'Jetzt veröffentlichen', sq: 'Publiko tani' },
  'social.schedule': { en: 'Schedule Post', de: 'Post planen', sq: 'Programo postimin' },
  'social.save_draft': { en: 'Save as Draft', de: 'Als Entwurf speichern', sq: 'Ruaj si draft' },
  'social.history': { en: 'Post History', de: 'Verlauf', sq: 'Historia e postimeve' },
  'social.autopost.label': { en: 'Auto-Post Automation', de: 'Auto-Post Automatisierung', sq: 'Automatizimi i Postimeve' },
  'social.autopost.desc': { en: 'When enabled, generated posts will be sent directly to social media upon clicking Publish.', de: 'Wenn aktiviert, werden generierte Posts beim Klicken auf Veröffentlichen direkt an Social Media gesendet.', sq: 'Kur aktivizohet, postimet do të dërgohen direkt në rrjete sociale me klikimin Publiko.' },
  'social.api.fb.title': { en: 'Facebook Graph API', de: 'Facebook Graph API', sq: 'Facebook Graph API' },
  'social.api.ig.title': { en: 'Instagram Business API', de: 'Instagram Business API', sq: 'Instagram Business API' },
  'social.api.token.label': { en: 'Access Token', de: 'Zugriffstoken', sq: 'Token i qasjes' },
  'social.api.id.label': { en: 'Entity ID', de: 'Entity ID', sq: 'ID e entitetit' },

  // --- AUTH (Login) ---
  'auth.has_account': { en: 'Already have an account?', de: 'Bereits ein Konto?', sq: 'Keni llogari?' },
  'auth.session_expired': { en: 'Your session has expired due to inactivity.', de: 'Deine Sitzung ist wegen Inaktivität abgelaufen.', sq: 'Seanca juaj ka skaduar për shkak të pasivitetit.' },
  'login.title': { en: 'Login', de: 'Anmelden', sq: 'Kyçuni' },
  'login.subtitle': { en: 'Access our solidarity community.', de: 'Zugang zu unserer Solidaritätsgemeinschaft.', sq: 'Hyni në komunitetin tonë të solidaritetit.' },
  'login.back': { en: 'Back', de: 'Zurück', sq: 'Kthehu' },
  'login.email.label': { en: 'Email Address', de: 'E-Mail Adresse', sq: 'Adresa e Email-it' },
  'login.email.placeholder': { en: 'name@example.com', de: 'name@beispiel.com', sq: 'emri@shembull.com' },
  'login.email.send': { en: 'Send Magic Link', de: 'Magic Link senden', sq: 'Dërgo Magic Link' },
  'login.password.label': { en: 'Password', de: 'Passwort', sq: 'Fjalëkalimi' },
  'login.password.forgot': { en: 'Forgot Password?', de: 'Passwort vergessen?', sq: 'Harruat fjalëkalimin?' },
  'login.submit': { en: 'Login', de: 'Einloggen', sq: 'Kyçuni' },
  'login.google': { en: 'Continue with Google', de: 'Weiter mit Google', sq: 'Vazhdo me Google' },
  'login.hero.title': { en: 'Welcome Back.', de: 'Willkommen zurück.', sq: 'Mirë se vini.' },
  'login.hero.desc': { en: 'Your contribution makes a difference. Log in to manage your membership.', de: 'Dein Beitrag macht den Unterschied. Melde dich an, um deine Mitgliedschaft zu verwalten.', sq: 'Kontributi juaj bën ndryshimin. Kyçuni për të menaxhuar anëtarësimin.' },
  'login.verifying': { en: 'Verifying...', de: 'Überprüfe...', sq: 'Duke verifikuar...' },
  'login.sent.title': { en: 'Magic Link Sent!', de: 'Link gesendet!', sq: 'Linku u dërgua!' },
  'login.sent.desc': { en: 'We sent a secure login link to:', de: 'Wir haben einen sicheren Link gesendet an:', sq: 'Ne dërguam një link të sigurt në:' },
  'login.sent.retry': { en: 'Send again', de: 'Erneut senden', sq: 'Dërgo sërish' },
  'login.method.password': { en: 'Password', de: 'Passwort', sq: 'Fjalëkalim' },
  'login.method.magic': { en: 'Magic Link', de: 'Magic Link', sq: 'Magic Link' },

  // --- REGISTRATION WIZARD ---
  'wizard.title': { en: 'Join Us', de: 'Mach mit', sq: 'Bashkohu me ne' },
  'wizard.step.1': { en: 'Account', de: 'Konto', sq: 'Llogaria' },
  'wizard.step.2': { en: 'Personal', de: 'Persönlich', sq: 'Personale' },
  'wizard.step.3': { en: 'Location', de: 'Standort', sq: 'Vendndodhja' },
  'wizard.step.4': { en: 'Verify', de: 'Prüfung', sq: 'Verifikimi' },
  'wizard.next': { en: 'Continue', de: 'Weiter', sq: 'Vazhdo' },
  'wizard.prev': { en: 'Back', de: 'Zurück', sq: 'Mbrapa' },
  'wizard.finish': { en: 'Finish', de: 'Abschließen', sq: 'Përfundo' },
  'wizard.success.title': { en: 'Check your email!', de: 'Prüfe deine E-Mails!', sq: 'Kontrolloni email-in!' },
  'wizard.success.desc': { en: 'We have sent a verification link.', de: 'Wir haben einen Bestätigungslink gesendet.', sq: 'Ne kemi dërguar një email verifikimi.' },

  // --- PROFILE SETUP & EDIT ---
  'setup.name.label': { en: 'Full Name', de: 'Vollständiger Name', sq: 'Emri i plotë' },
  'setup.phone.label': { en: 'Phone Number', de: 'Telefonnummer', sq: 'Numri i telefonit' },
  'profile.edit': { en: 'Edit Profile', de: 'Profil bearbeiten', sq: 'Ndrysho Profilin' },
  'profile.identity': { en: 'Identity', de: 'Identität', sq: 'Identiteti' },
  'profile.contact': { en: 'Contact', de: 'Kontakt', sq: 'Kontakt' },
  'profile.address': { en: 'Address', de: 'Adresse', sq: 'Adresa' },
  'profile.invoice_method': { en: 'Invoice Delivery', de: 'Rechnungsversand', sq: 'Mënyra e Faturimit' },

  // --- DASHBOARD ---
  'dash.welcome': { en: 'Welcome', de: 'Willkommen', sq: 'Mirë se vini' },
  'dash.subtitle': { en: 'Your membership overview', de: 'Deine Mitgliedschaftsübersicht', sq: 'Pasqyra e anëtarësimit tuaj' },
  'dash.intro': { en: 'Here is your overview of your contribution and community in', de: 'Hier ist deine Übersicht über deinen Beitrag und die Gemeinschaft in', sq: 'Këtu keni pasqyrën e kontributit tuaj dhe komunitetit në' },
  'dash.status.title': { en: 'Your Status', de: 'Dein Status', sq: 'Statusi Juaj' },
  'dash.status.active_paid': { en: 'Active / Paid', de: 'Aktiv / Bezahlt', sq: 'Aktiv / Paguar' },
  'dash.status.pending': { en: 'Pending', de: 'Ausstehend', sq: 'Në pritje' },
  
  // Invoice Card
  'dash.payment.title': { en: 'Membership Fee', de: 'Mitgliedsbeitrag', sq: 'Kuota e Anëtarësisë' },
  'dash.payment.qr': { en: 'Generate QR Bill', de: 'QR-Rechnung erstellen', sq: 'Gjenero Faturën QR' },
  'dash.invoice.open': { en: 'Open', de: 'Offen', sq: 'E Hapur' },
  'dash.invoice.amount': { en: 'Amount to pay', de: 'Betrag zu zahlen', sq: 'Shuma për pagesë' },
  'dash.invoice.due': { en: 'Due date', de: 'Fällig am', sq: 'Afati' },
  
  // Paid State
  'dash.invoice.all_paid_title': { en: 'Everything paid!', de: 'Alles bezahlt!', sq: 'Gjithçka e paguar!' },
  'dash.invoice.all_paid_desc': { en: 'Thank you for your contribution for year', de: 'Danke für deinen Beitrag für das Jahr', sq: 'Faleminderit për kontributit tuaj për vitin' },
  'dash.invoice.membership': { en: 'Membership', de: 'Mitgliedschaft', sq: 'Anëtarësia' },
  
  // Waiting State
  'dash.invoice.waiting_title': { en: 'Membership', de: 'Mitgliedschaft', sq: 'Anëtarësia' },
  'dash.invoice.waiting_desc': { en: 'Invoice for {year} has not been issued yet. You will be notified when ready.', de: 'Die Rechnung für {year} wurde noch nicht erstellt. Du wirst benachrichtigt.', sq: 'Fatura për vitin {year} ende nuk është lëshuar. Do të njoftoheni sapo të jetë gati.' },
  'dash.invoice.waiting_badge': { en: 'Pending issuance', de: 'Noch nicht verrechnet', sq: 'Në pritje të lëshimit' },

  'dash.history': { en: 'Payment History', de: 'Zahlungshistorie', sq: 'Historiku i Pagesave' },
  'dash.bank_details': { en: 'Bank Details', de: 'Bankverbindung', sq: 'Të Dhënat Bankare' },
  'dash.neighborhood.title': { en: 'My Neighborhood', de: 'Mein Quartier', sq: 'Lagja Ime' },
  'dash.qr.title': { en: 'Swiss QR Bill', de: 'Schweizer QR-Rechnung', sq: 'Fatura QR Zvicerane' },
  
  // Neighbors Section
  'dash.neighbors.title': { en: 'Your Neighbors', de: 'Deine Nachbarn', sq: 'Fqinjët Tuaj' },
  'dash.neighbors.subtitle': { en: 'Members of', de: 'Mitglieder von', sq: 'Anëtarët e' },
  'dash.neighbors.families': { en: 'Families', de: 'Familien', sq: 'Familjet' },
  'dash.neighbors.family_prefix': { en: 'Family', de: 'Familie', sq: 'Familja' },
  'dash.neighbors.individuals': { en: 'Individuals', de: 'Einzelpersonen', sq: 'Individët' },
  'dash.neighbors.first': { en: 'You are the first member here!', de: 'Du bist das erste Mitglied hier!', sq: 'Ju jeni anëtari i parë këtu!' },

  // Manager Section
  'dash.manager.title': { en: 'Your Manager', de: 'Dein Manager', sq: 'Manageri Juaj' },
  'dash.manager.none': { en: 'No Manager', de: 'Kein Manager', sq: 'Pa Manager' },
  'dash.manager.email': { en: 'Email', de: 'E-Mail', sq: 'Email' },
  'dash.manager.call': { en: 'Call', de: 'Anrufen', sq: 'Telefono' },

  // Requests Section
  'dash.requests.title': { en: 'My Inquiries', de: 'Meine Anfragen', sq: 'Kërkesat e Mia' },
  'dash.requests.new': { en: 'New Inquiry', de: 'Neue Anfrage', sq: 'Kërkesë e Re' },
  'dash.requests.type': { en: 'Type', de: 'Typ', sq: 'Lloji' },
  'dash.requests.subject': { en: 'Subject', de: 'Betreff', sq: 'Subjekti' },
  'dash.requests.message': { en: 'Message', de: 'Nachricht', sq: 'Mesazhi' },
  'dash.requests.submit': { en: 'Submit Request', de: 'Anfrage senden', sq: 'Dërgo Kërkesën' },
  'req.type.DONATION': { en: 'Donation', de: 'Spende', sq: 'Donacion' },
  'req.type.PROJECT': { en: 'Project Proposal', de: 'Projektvorschlag', sq: 'Propozim Projekti' },
  'req.type.GENERAL': { en: 'General Inquiry', de: 'Allgemein', sq: 'Të përgjithshme' },
  'req.status.OPEN': { en: 'Open', de: 'Offen', sq: 'E Hapur' },
  'req.status.IN_PROGRESS': { en: 'In Progress', de: 'In Bearbeitung', sq: 'Në Përpunim' },
  'req.status.DONE': { en: 'Resolved', de: 'Erledigt', sq: 'E Përfunduar' },
  'req.status.REJECTED': { en: 'Rejected', de: 'Abgelehnt', sq: 'E Refuzuar' },

  // Community Pulse
  'dash.community.title': { en: 'Community Pulse', de: 'Community Puls', sq: 'Pulsi i Komunitetit' },
  'dash.community.active_members': { en: 'Active members in your neighborhood', de: 'Aktive Mitglieder in deinem Quartier', sq: 'Anëtarë aktivë në lagjen tuaj' },
  'dash.community.quote': { en: 'Unity makes strength. Thank you for being part of the change!', de: 'Einigkeit macht stark. Danke, dass du Teil des Wandels bist!', sq: 'Bashkimi bën fuqinë. Faleminderit që jeni pjesë e ndryshimit!' },
  
  // --- DASHBOARD INSIGHTS ---
  'dash.insights.active': { en: 'Active Neighbors', de: 'Aktive Nachbarn', sq: 'Fqinjët Aktivë' },
  'dash.insights.participation': { en: 'Participation Rate', de: 'Beteiligungsrate', sq: 'Shkalla e Pjesëmarrjes' },
  'dash.insights.of': { en: 'of', de: 'von', sq: 'nga' },
  'dash.insights.members': { en: 'members', de: 'Mitgliedern', sq: 'anëtarë' },
  'dash.insights.desc': { en: 'Members who have paid the annual fee.', de: 'Mitglieder, die den Jahresbeitrag bezahlt haben.', sq: 'Anëtarët që kanë paguar kuotën vjetore.' },

  // --- REP DASHBOARD ---
  'rep.title': { en: 'Representative', de: 'Vertreter', sq: 'Përfaqësuesi' },
  'rep.cash_balance': { en: 'Cash Balance', de: 'Kassenbestand', sq: 'Gjendja në Kasë' },
  'rep.deposit': { en: 'Deposit to Bank', de: 'Einzahlung Bank', sq: 'Depozito në Bankë' },
  'rep.collection': { en: 'Collection', de: 'Inkasso', sq: 'Inkasimi' },
  'rep.expenses': { en: 'Expenses', de: 'Ausgaben', sq: 'Shpenzimet' },
  'rep.tasks': { en: 'Tasks', de: 'Aufgaben', sq: 'Detyrat' },
  'rep.register_member': { en: 'Register Member', de: 'Mitglied registrieren', sq: 'Regjistro Anëtar' },
  'rep.search_member': { en: 'Search member...', de: 'Mitglied suchen...', sq: 'Kërko banor...' },
  'rep.collect': { en: 'Collect Payment', de: 'Kassieren', sq: 'Arkëto' },
  'rep.paid': { en: 'Paid', de: 'Bezahlt', sq: 'Paguar' },
  'rep.new_expense': { en: 'New Expense', de: 'Neue Ausgabe', sq: 'Shto Shpenzim' },
  'rep.expense_history': { en: 'Expense History', de: 'Ausgabenhistorie', sq: 'Historiku i Shpenzimeve' },
  'rep.no_tasks': { en: 'No active tasks.', de: 'Keine aktiven Aufgaben.', sq: 'Nuk keni detyra aktive.' },

  // --- ADMIN ---
  'admin.hub.title': { en: 'Admin Hub', de: 'Admin Zentrale', sq: 'Admin Hub' },
  'admin.hub.subtitle': { en: 'Full control of the association.', de: 'Volle Kontrolle über den Verein.', sq: 'Kontrolli i plotë i shoqatës.' },
  'admin.tab.analytics': { en: 'Dashboard', de: 'Übersicht', sq: 'Pasqyra' },
  'admin.tab.users': { en: 'Members', de: 'Mitglieder', sq: 'Anëtarët' },
  'admin.tab.data_quality': { en: 'Data Quality', de: 'Datenqualität', sq: 'Cilësia e të Dhënave' },
  'admin.tab.board': { en: 'Board', de: 'Vorstand', sq: 'Kryesia' },
  'admin.tab.events': { en: 'Events', de: 'Events', sq: 'Ngjarjet' },
  'admin.tab.neighborhoods': { en: 'Neighborhoods', de: 'Nachbarschaften', sq: 'Lagjet' },
  'admin.tab.website': { en: 'Website', de: 'Webseite', sq: 'Website' },
  'admin.tab.social': { en: 'Social AI', de: 'Social AI', sq: 'Social AI' },
  'admin.tab.finance': { en: 'Finance', de: 'Finanzen', sq: 'Financat' },
  'admin.tab.accounting': { en: 'Accounting', de: 'Buchhaltung', sq: 'Kontabiliteti' },
  'admin.tab.expenses': { en: 'Expenses', de: 'Ausgaben', sq: 'Shpenzimet' },
  'admin.tab.statistics': { en: 'Statistics', de: 'Statistiken', sq: 'Statistikat' },
  'admin.tab.settings': { en: 'Settings', de: 'Einstellungen', sq: 'Cilësimet' },
  'admin.tasks.title': { en: 'Global Tasks', de: 'Aufgaben', sq: 'Detyrat Globale' },
  'admin.tasks.none': { en: 'No pending tasks.', de: 'Keine offenen Aufgaben.', sq: 'Nuk ka detyra.' },
  
  'admin.members.title': { en: 'Member Management', de: 'Mitgliederverwaltung', sq: 'Menaxhimi i Anëtarëve' },
  'admin.members.search': { en: 'Search members...', de: 'Mitglieder suchen...', sq: 'Kërko anëtarët...' },
  'admin.members.add_new': { en: 'Add Member', de: 'Mitglied hinzufügen', sq: 'Shto Anëtar' },
  'admin.members.details': { en: 'Member Details', de: 'Mitgliederdetails', sq: 'Detajet e Anëtarit' },
  'admin.members.reminders': { en: 'Reminders', de: 'Erinnerungen', sq: 'Kujtesat' },
  'admin.members.add_reminder': { en: 'Add Reminder', de: 'Erinnerung +', sq: 'Shto Kujtesë' },
  'admin.members.internal_notes': { en: 'Internal Notes', de: 'Interne Notizen', sq: 'Shënime Interne' },
  'admin.confirm_delete': { en: 'Are you sure?', de: 'Sind Sie sicher?', sq: 'A jeni i sigurt?' },

  // --- ADMIN FINANCE ---
  'admin.finance.forecast': { en: 'Forecast & Planning', de: 'Prognose & Planung', sq: 'Parashikimi & Planifikimi' },
  'admin.finance.overview': { en: 'Overview', de: 'Übersicht', sq: 'Pasqyra' },
  'admin.finance.invoices': { en: 'Invoices & Drafts', de: 'Rechnungen & Entwürfe', sq: 'Faturat & Draftet' },
  'admin.finance.dunning': { en: 'Dunning', de: 'Mahnwesen', sq: 'Mahnwesen' },
  'admin.finance.settings': { en: 'Settings', de: 'Einstellungen', sq: 'Cilësimet' },
  'admin.finance.collected': { en: 'Total Collected', de: 'Einnahmen Total', sq: 'Të hyrat Totale' },
  'admin.finance.open': { en: 'Open Invoices', de: 'Offene Rechnungen', sq: 'Faturat e Hapura' },
  'admin.finance.overdue': { en: 'Overdue', de: 'Überfällig', sq: 'Të papaguara' },
  'admin.finance.potential': { en: 'Potential Revenue', de: 'Potenzieller Umsatz', sq: 'Të hyrat Potenciale' },
  'admin.finance.recent': { en: 'Recent Invoices', de: 'Letzte Rechnungen', sq: 'Faturat e fundit' },
  'admin.finance.invoiceNum': { en: 'Invoice #', de: 'Rechnungs-Nr.', sq: 'Nr. Faturës' },
  'admin.finance.amount': { en: 'Amount', de: 'Betrag', sq: 'Shuma' },
  'admin.finance.date': { en: 'Date', de: 'Datum', sq: 'Data' },
  'admin.finance.member': { en: 'Member', de: 'Mitglied', sq: 'Anëtari' },
  'admin.finance.status': { en: 'Status', de: 'Status', sq: 'Statusi' },
  'admin.finance.create': { en: 'Create Invoice', de: 'Rechnung erstellen', sq: 'Krijo Faturë' },
  'admin.finance.verify': { en: 'Verify Drafts', de: 'Entwürfe prüfen', sq: 'Verifiko Draftet' },
  'admin.finance.markPaid': { en: 'Mark Paid', de: 'Als bezahlt markieren', sq: 'Shëno të paguar' },

  // --- ADMIN STATISTICS ---
  'admin.stats.revenue': { en: 'Revenue', de: 'Einnahmen', sq: 'Të Hyrat' },
  'admin.stats.late': { en: 'Late Payers', de: 'Säumige Zahler', sq: 'Vonesat' },
  'admin.stats.unpaid': { en: 'Open / Unpaid', de: 'Offen / Unbezahlt', sq: 'Të Hapura' },
  'admin.stats.participation': { en: 'Avg. Participation', de: 'Durchs. Beteiligung', sq: 'Pjesëmarrja Mesatare' },
  'admin.stats.neighborhoodPerf': { en: 'Neighborhood Performance', de: 'Leistung der Nachbarschaften', sq: 'Performanca e Lagjeve' },
  'admin.stats.history': { en: 'Revenue Trends', de: 'Umsatzentwicklung', sq: 'Trendi i Të Hyrave' },
  'admin.stats.memberDetail': { en: 'Member Payment Detail', de: 'Mitglieder Zahlungsdetails', sq: 'Detajet e Pagesave' },
  'admin.stats.totalMembers': { en: 'Total Members', de: 'Mitglieder Total', sq: 'Gjithsej Anëtarë' },
  'admin.stats.payers': { en: 'Payers', de: 'Zahler', sq: 'Paguesit' },

  // --- ADMIN EXPENSES ---
  'admin.expenses.title': { en: 'Expenses', de: 'Ausgaben', sq: 'Shpenzimet' },
  'admin.expenses.all': { en: 'All Expenses', de: 'Alle Ausgaben', sq: 'Të Gjitha' },
  'admin.expenses.pending': { en: 'Pending / Review', de: 'Offen / Prüfung', sq: 'Në Pritje' },
  'admin.expenses.paid': { en: 'Booked', de: 'Verbucht', sq: 'Të Libruara' },
  'admin.expenses.vendor': { en: 'Vendor', de: 'Lieferant', sq: 'Furnitori' },
  'admin.expenses.description': { en: 'Description', de: 'Beschreibung', sq: 'Përshkrimi' },
  'admin.expenses.category': { en: 'Expense Account', de: 'Aufwandskonto', sq: 'Llogaria e Shpenzimit' },
  'admin.expenses.paymentAcc': { en: 'Payment Account', de: 'Zahlungskonto', sq: 'Llogaria e Pagesës' },
  'admin.expenses.scan': { en: 'Scan Receipt', de: 'Beleg Scannen', sq: 'Skano Faturën' },
  'admin.expenses.manual': { en: 'Manual Entry', de: 'Manuell', sq: 'Manuale' },
  'admin.expenses.book': { en: 'Book', de: 'Verbuchen', sq: 'Libro' },
  'admin.expenses.save': { en: 'Save Expense', de: 'Ausgabe speichern', sq: 'Ruaj Shpenzimin' },

  // --- ADMIN ACCOUNTING ---
  'admin.accounting.title': { en: 'Accounting', de: 'Buchhaltung', sq: 'Kontabiliteti' },
  'admin.accounting.balanceSheet': { en: 'Balance Sheet', de: 'Bilanz', sq: 'Bilanci' },
  'admin.accounting.incomeStatement': { en: 'Income Statement', de: 'Erfolgsrechnung', sq: 'Pasqyra e të Ardhurave' },
  'admin.accounting.journal': { en: 'Journal', de: 'Journal', sq: 'Ditari' },
  'admin.accounting.accounts': { en: 'Chart of Accounts', de: 'Kontenplan', sq: 'Plani Kontabël' },
  'admin.accounting.assets': { en: 'Assets', de: 'Aktiven', sq: 'Aktivet' },
  'admin.accounting.liabilities': { en: 'Liabilities', de: 'Passiven', sq: 'Pasivet' },
  'admin.accounting.revenue': { en: 'Revenue', de: 'Ertrag', sq: 'Të Ardhurat' },
  'admin.accounting.expense': { en: 'Expense', de: 'Aufwand', sq: 'Shpenzimet' },
  'admin.accounting.profit': { en: 'Net Profit', de: 'Jahresergebnis', sq: 'Fitimi Neto' },
  'admin.accounting.debit': { en: 'Debit', de: 'Soll', sq: 'Debi' },
  'admin.accounting.credit': { en: 'Credit', de: 'Haben', sq: 'Kredi' },
  'admin.accounting.closeYear': { en: 'Close Year', de: 'Jahr abschließen', sq: 'Mbyll Vitin' },
  'admin.accounting.newBooking': { en: 'New Booking', de: 'Neue Buchung', sq: 'Regjistrim i Ri' },
  'admin.accounting.importPayments': { en: 'Import Payments', de: 'Zahlungen importieren', sq: 'Importo Pagesat' },

  // --- EVENTS ---
  'events.title': { en: 'Upcoming Events', de: 'Kommende Events', sq: 'Ngjarjet e Ardhshme' },
  'events.subtitle': { en: 'Participate in our actions.', de: 'Nimm an unseren Aktionen teil.', sq: 'Merrni pjesë në aksionet tona.' },
  'events.desc': { 
    en: 'Discover upcoming gatherings, cultural festivals, and community projects. Be part of our vibrant network.', 
    de: 'Entdecken Sie kommende Treffen, Kulturfestivals und Gemeinschaftsprojekte. Werden Sie Teil unseres lebendigen Netzwerks.', 
    sq: 'Zbuloni tubimet e ardhshme, festivalet kulturore dhe projektet komunitare. Bëhuni pjesë e rrjetit tonë të gjallë.' 
  },
  'events.view_all': { en: 'View All', de: 'Alle ansehen', sq: 'Shiko të gjitha' },
  'events.join': { en: 'Join', de: 'Teilnehmen', sq: 'Bashkohu' },

  // --- FIELDS & STATUS ---
  'field.salutation': { en: 'Salutation', de: 'Anrede', sq: 'Përshëndetja' },
  'field.firstName': { en: 'First Name', de: 'Vorname', sq: 'Emri' },
  'field.lastName': { en: 'Last Name', de: 'Nachname', sq: 'Mbiemri' },
  'field.email': { en: 'Email', de: 'E-Mail', sq: 'Email' },
  'field.phone': { en: 'Phone', de: 'Telefon', sq: 'Telefoni' },
  'field.street': { en: 'Street', de: 'Strasse', sq: 'Rruga' },
  'field.zip': { en: 'ZIP', de: 'PLZ', sq: 'Kodi Postar' },
  'field.city': { en: 'City', de: 'Ort', sq: 'Qyteti' },
  'field.country': { en: 'Country', de: 'Land', sq: 'Shteti' },
  'field.birthdate': { en: 'Birthdate', de: 'Geburtsdatum', sq: 'Datëlindja' },
  'field.category': { en: 'Category', de: 'Kategorie', sq: 'Kategoria' },
  'field.status': { en: 'Status', de: 'Status', sq: 'Statusi' },

  'status.active': { en: 'Active', de: 'Aktiv', sq: 'Aktiv' },
  'status.pending': { en: 'Pending', de: 'Ausstehend', sq: 'Në pritje' },
  'status.inactive': { en: 'Inactive', de: 'Inaktiv', sq: 'Joaktiv' },
  'status.all': { en: 'All', de: 'Alle', sq: 'Të gjitha' },

  'cat.individual': { en: 'Individual', de: 'Einzelperson', sq: 'Individual' },
  'cat.family': { en: 'Family', de: 'Familie', sq: 'Familjar' },
  'cat.donor': { en: 'Donor', de: 'Spender', sq: 'Donator' },

  'btn.save': { en: 'Save', de: 'Speichern', sq: 'Ruaj' },

  'error.boundary.title': { en: 'This page could not be loaded', de: 'Diese Seite konnte nicht geladen werden', sq: 'Kjo faqe nuk mund të ngarkohej' },
  'error.boundary.text': { en: 'Something went wrong while displaying this page. Your data is unaffected.', de: 'Beim Anzeigen dieser Seite ist etwas schiefgelaufen. Ihre Daten sind davon nicht betroffen.', sq: 'Diçka shkoi keq gjatë shfaqjes së kësaj faqeje. Të dhënat tuaja nuk janë prekur.' },
  'error.boundary.retry': { en: 'Try again', de: 'Erneut versuchen', sq: 'Provo përsëri' },

  // --- FOOTER ---
  'footer.tagline': { en: 'Together for our home. The diaspora and Koretin, one step towards the future.', de: 'Gemeinsam für unsere Heimat. Die Diaspora und Koretin, einen Schritt in die Zukunft.', sq: 'Bashkë për vendlindjen tonë. Diaspora dhe Koretini në një hap drejt të ardhmes.' },
  'footer.rights': { en: 'All rights reserved.', de: 'Alle Rechte vorbehalten.', sq: 'Të gjitha të drejtat e rezervuara.' },
  'footer.address.fallback': { en: 'Koretin, Kosovo', de: 'Koretin, Kosovo', sq: 'Koretin, Kosovë' },
  'footer.email.fallback': { en: 'info@koretini.org', de: 'info@koretini.org', sq: 'info@koretini.org' },

  // --- UEBER UNS ---
  'about.badge': { en: 'Global network', de: 'Globales Netzwerk', sq: 'Rrjet global' },
  'about.title': { en: 'About us', de: 'Über uns', sq: 'Rreth Nesh' },
  'about.intro': { en: 'The association is a bridge between the home village and the diaspora. We are committed to developing our community through concrete projects and solidarity.', de: 'Der Verein ist die Brücke zwischen der Heimat und der Diaspora. Wir setzen uns mit konkreten Projekten und Solidarität für die Entwicklung unserer Gemeinschaft ein.', sq: 'Shoqata është urë lidhëse mes vendlindjes dhe diasporës. Ne jemi të përkushtuar për zhvillimin e komunitetit tonë përmes projekteve konkrete dhe solidaritetit.' },

  // --- KORETINI LIVE / PROJEKTE ---
  'live.cat.health': { en: 'Health', de: 'Gesundheit', sq: 'Shëndetësia' },
  'live.cat.health.desc': { en: 'Support for the local clinic', de: 'Unterstützung für die Ambulanz', sq: 'Përkrahje për ambulancën' },
  'live.cat.water': { en: 'Water & nature', de: 'Wasser & Natur', sq: 'Uji & Natyra' },
  'live.cat.water.desc': { en: 'Caring for the environment', de: 'Pflege der Umwelt', sq: 'Mirëmbajtja e ambientit' },
  'live.cat.energy': { en: 'Energy', de: 'Energie', sq: 'Energjia' },
  'live.cat.energy.desc': { en: 'Modern infrastructure', de: 'Moderne Infrastruktur', sq: 'Infrastruktura moderne' },
  'live.cat.education': { en: 'Education', de: 'Bildung', sq: 'Arsimi' },
  'live.cat.education.desc': { en: 'Educating the next generation', de: 'Bildung für die nächste Generation', sq: 'Edukimi i gjeneratave' },
  'live.cat.sport': { en: 'Sport', de: 'Sport', sq: 'Sporti' },
  'live.cat.sport.desc': { en: 'Sporting activities', de: 'Sportliche Aktivitäten', sq: 'Aktivitete sportive' },

  // --- EVENTS & NEWS (oeffentlich) ---
  'events.badge': { en: 'Koretini Events', de: 'Koretini Events', sq: 'Koretini Events' },
  'events.info_only': { en: 'Info only', de: 'Nur Information', sq: 'Vetëm informacion' },
  'events.soon': { en: 'Coming soon', de: 'Demnächst', sq: 'Së shpejti' },
  'events.free_entry': { en: 'Entry is free & public', de: 'Eintritt frei & öffentlich', sq: 'Hyrja është e lirë & publike' },
  'events.registration_failed': { en: 'Registration failed', de: 'Anmeldung fehlgeschlagen', sq: 'Regjistrimi dështoi' },
  'news.page.badge': { en: 'Diaspora News', de: 'Diaspora News', sq: 'Diaspora News' },

  // --- TWINT / SPENDEN ---
  'twint.support': { en: 'Support us with TWINT', de: 'Mit TWINT unterstützen', sq: 'Na përkrahni me TWINT' },
  'twint.open_app': { en: 'Open TWINT app', de: 'TWINT-App öffnen', sq: 'Hap aplikacionin TWINT' },

  // --- ANMELDUNG / REGISTRIERUNG ---
  'auth.image_alt': { en: 'Humanitarian mission', de: 'Humanitäre Mission', sq: 'Mision humanitar' },
  'auth.join_title': { en: 'Join us', de: 'Mitmachen', sq: 'Bashkohu me ne' },
  'auth.join_desc': { en: 'Secure passwordless login with a magic link.', de: 'Sichere Anmeldung ohne Passwort per Magic Link.', sq: 'Qasje e sigurt pa fjalëkalim me Magic Link.' },
  'auth.email_label': { en: 'Email address', de: 'E-Mail-Adresse', sq: 'Adresa e e-mailit' },
  'auth.send_link': { en: 'Send magic link', de: 'Magic Link senden', sq: 'Dërgo Magic Link' },
  'auth.link_sent': { en: 'Link sent!', de: 'Link gesendet!', sq: 'Linku u dërgua!' },
  'auth.link_sent_desc': { en: 'Check your inbox for a secure login link. It expires in 15 minutes.', de: 'Prüfen Sie Ihr Postfach: Der sichere Anmeldelink ist 15 Minuten gültig.', sq: 'Kontrolloni postën tuaj për linkun e sigurt. Ai skadon pas 15 minutash.' },

  // --- FORMULARE: BEISPIELWERTE ---
  'ph.password': { en: '••••••••', de: '••••••••', sq: '••••••••' },
  'ph.firstname': { en: 'John', de: 'Hans', sq: 'Filan' },
  'ph.lastname': { en: 'Doe', de: 'Muster', sq: 'Fisteku' },
  'ph.fullname': { en: 'First name and surname', de: 'Vor- und Nachname', sq: 'Emri Mbiemri' },
  'ph.phone': { en: '+41 79 000 00 00', de: '+41 79 000 00 00', sq: '+41 79 000 00 00' },
  'ph.street': { en: 'Bahnhofstrasse 12', de: 'Bahnhofstrasse 12', sq: 'Bahnhofstrasse 12' },
  'ph.zip': { en: '8000', de: '8000', sq: '8000' },
  'ph.city': { en: 'Zurich', de: 'Zürich', sq: 'Zürich' },
  'ph.country': { en: 'Switzerland', de: 'Schweiz', sq: 'Zvicër' },
  'ph.address_full': { en: 'Example Street 1, 8000 Zurich', de: 'Musterstrasse 1, 8000 Zürich', sq: 'Rruga shembull 1, 8000 Zürich' },
  'ph.email_example': { en: 'name@example.com', de: 'name@beispiel.ch', sq: 'emri@shembull.com' },
  'ph.search_neighborhood': { en: 'Search neighborhood...', de: 'Nachbarschaft suchen...', sq: 'Kërko lagjen...' },
  'salutation.ms': { en: 'Ms.', de: 'Frau', sq: 'Znj.' },

  'form.invoice_delivery': { en: 'Invoice delivery', de: 'Rechnungsversand', sq: 'Dërgimi i faturës' },
  'form.invoice_preference': { en: 'Invoice preference', de: 'Rechnungsversand', sq: 'Preferenca e faturës' },
  'form.fee_hint': { en: 'Determines your membership fee.', de: 'Bestimmt Ihren Mitgliederbeitrag.', sq: 'Përcakton shumën e anëtarësisë tuaj.' },
  'form.email_invoice_hint': { en: 'Your email address is used to send the annual membership invoice.', de: 'Ihre E-Mail-Adresse wird für den jährlichen Beitragsversand verwendet.', sq: 'E-maili juaj do të përdoret për të dërguar faturën e anëtarësisë çdo vit.' },

  // --- DIVERSES ---
  'nav.back_home': { en: 'Back to home', de: 'Zurück zur Startseite', sq: 'Kthehu në ballinë' },
  'neighborhood.register': { en: 'Register neighborhood', de: 'Nachbarschaft anmelden', sq: 'Regjistro lagjen' },
  'neighborhood.details': { en: 'View details', de: 'Details ansehen', sq: 'Shiko detajet' },

  // --- MITGLIEDERBEREICH ---
  'dash.badge': { en: 'Member area', de: 'Mitgliederbereich', sq: 'Zona e anëtarëve' },
  'dash.update.title': { en: 'Please update your details', de: 'Bitte Daten ergänzen', sq: 'Ju lutem plotësoni të dhënat' },
  'dash.update.requested': { en: 'The board has asked you to check your profile details.', de: 'Der Vorstand bittet Sie, Ihre Profildaten zu prüfen.', sq: 'Kryesia ju lut të verifikoni të dhënat e profilit tuaj.' },
  'dash.update.missing': { en: 'Please complete your profile. Missing: {fields}', de: 'Bitte vervollständigen Sie Ihr Profil. Es fehlt: {fields}', sq: 'Ju lutem plotësoni profilin tuaj. Mungon: {fields}' },
  'dash.update.now': { en: 'Complete now', de: 'Jetzt ergänzen', sq: 'Plotëso tani' },
  'dash.saved': { en: 'Details updated.', de: 'Daten erfolgreich aktualisiert.', sq: 'Të dhënat u përditësuan.' },
  'dash.no_email': { en: 'No email address on file.', de: 'Keine E-Mail-Adresse hinterlegt.', sq: 'Nuk ka adresë e-maili të regjistruar.' },
  'dash.request_sent': { en: 'Request sent.', de: 'Aufforderung gesendet.', sq: 'Kërkesa u dërgua.' },
  'dash.fill_all': { en: 'Please fill in all fields.', de: 'Bitte alle Felder ausfüllen.', sq: 'Ju lutem plotësoni të gjitha fushat.' },
  'dash.no_payments': { en: 'No payments yet.', de: 'Noch keine Zahlungen.', sq: 'Ende asnjë pagesë.' },
  'dash.no_inquiries': { en: 'No enquiries yet.', de: 'Noch keine Anfragen.', sq: 'Ende asnjë kërkesë.' },
  'dash.login_here': { en: 'Log in here', de: 'Hier einloggen', sq: 'Kyçu këtu' },
  'dash.manage_profile': { en: 'Manage profile', de: 'Profil verwalten', sq: 'Menaxho profilin' },
  'dash.save_data': { en: 'Save details', de: 'Daten speichern', sq: 'Ruaj të dhënat' },
  'dash.invite_update': { en: 'Invite member to update', de: 'Zur Aktualisierung einladen', sq: 'Fto për përditësim' },
  'dash.nb_finance': { en: 'Neighborhood finances', de: 'Finanzen der Nachbarschaft', sq: 'Financat e lagjes' },
  'dash.manager_view': { en: 'Manager view', de: 'Ansicht Verantwortliche', sq: 'Pamja e menaxherit' },
  'dash.all_paid': { en: 'All paid. No open invoices in this neighborhood.', de: 'Alles bezahlt. Keine offenen Rechnungen in dieser Nachbarschaft.', sq: 'Gjithçka e paguar. Asnjë faturë e hapur në këtë lagje.' },
  'dash.incomplete_profile': { en: 'Incomplete profile', de: 'Profil unvollständig', sq: 'Profil i paplotësuar' },
  'dash.download_pdf': { en: 'Download PDF', de: 'PDF herunterladen', sq: 'Shkarko PDF' },

  // --- RECHNUNGSBELEG ---
  'invoice.heading': { en: 'INVOICE', de: 'RECHNUNG', sq: 'FATURË' },
  'invoice.billed_to': { en: 'Billed to:', de: 'Rechnung an:', sq: 'Faturuar për:' },
  'invoice.description': { en: 'Description', de: 'Beschreibung', sq: 'Përshkrimi' },
  'invoice.amount': { en: 'Amount', de: 'Betrag', sq: 'Shuma' },
  'invoice.total': { en: 'Total due', de: 'Gesamtbetrag', sq: 'Total për pagesë' },
  'invoice.thanks': { en: 'Thank you for supporting our community. Your contribution matters.', de: 'Danke, dass Sie unsere Gemeinschaft unterstützen. Ihr Beitrag zählt.', sq: 'Faleminderit që mbështesni komunitetin tonë. Kontributi juaj është i çmuar.' },

  // --- VORSTANDS-DASHBOARD ---
  'board.title': { en: 'Board dashboard', de: 'Vorstands-Dashboard', sq: 'Paneli i kryesisë' },
  'board.subtitle': { en: 'Overview of the association, finances and enquiries.', de: 'Übersicht über Verein, Finanzen und Anfragen.', sq: 'Përmbledhje e shoqatës, financave dhe kërkesave.' },
  'board.invoices': { en: 'Invoices', de: 'Rechnungen', sq: 'Faturat' },
  'board.search_member': { en: 'Search member or neighborhood...', de: 'Mitglied oder Nachbarschaft suchen...', sq: 'Kërko anëtar ose lagje...' },
  'board.no_results': { en: 'No results.', de: 'Keine Ergebnisse.', sq: 'Asnjë rezultat.' },
  'board.search_hint': { en: 'Search for members to see details...', de: 'Nach Mitgliedern suchen, um Details zu sehen...', sq: 'Kërkoni anëtarë për të parë detajet...' },
  'board.paid': { en: 'Paid', de: 'Bezahlt', sq: 'Paguar' },
  'board.top_neighborhoods': { en: 'Top 5 neighborhoods (CHF)', de: 'Top 5 Nachbarschaften (CHF)', sq: 'Top 5 lagjet (CHF)' },
  'board.lowest_contributions': { en: 'Lowest contributions (CHF)', de: 'Geringste Beiträge (CHF)', sq: 'Kontributet më të ulëta (CHF)' },
  'board.minutes': { en: 'Board minutes', de: 'Vorstandsprotokolle', sq: 'Procesverbalet e kryesisë' },
  'board.no_minutes': { en: 'No minutes available.', de: 'Keine Protokolle vorhanden.', sq: 'Nuk ka procesverbale.' },
  'board.inquiries': { en: 'Enquiries & feedback', de: 'Anfragen & Feedback', sq: 'Kërkesat & reagimet' },
  'board.admin_note': { en: 'Internal note', de: 'Interne Notiz', sq: 'Shënim i brendshëm' },
  'board.no_inquiries': { en: 'No enquiries available.', de: 'Keine Anfragen vorhanden.', sq: 'Nuk ka kërkesa.' },
  'board.no_entries': { en: 'No entries.', de: 'Keine Einträge.', sq: 'Asnjë hyrje.' },
  'board.attendees': { en: 'Attendees', de: 'Teilnehmende', sq: 'Pjesëmarrësit' },
  'board.agenda': { en: 'Agenda & decisions', de: 'Traktanden & Beschlüsse', sq: 'Rendi i ditës & vendimet' },

  // --- VERTRETUNG VOR ORT ---
  'rep.name_required': { en: 'Name is required.', de: 'Name ist erforderlich.', sq: 'Emri është i detyrueshëm.' },
  'rep.neighborhood_required': { en: 'Neighborhood is required.', de: 'Nachbarschaft ist erforderlich.', sq: 'Lagjja është e detyrueshme.' },
  'rep.amount_eur': { en: 'Amount (EUR)?', de: 'Betrag (EUR)?', sq: 'Shuma (EUR)?' },
  'rep.insufficient_funds': { en: 'Insufficient funds.', de: 'Nicht genügend Mittel.', sq: 'Mjete të pamjaftueshme.' },
  'rep.new_task': { en: 'New task...', de: 'Neue Aufgabe...', sq: 'Detyrë e re...' },
  'rep.complete': { en: 'Complete', de: 'Abschliessen', sq: 'Përfundo' },
  'rep.completed': { en: 'Completed', de: 'Abgeschlossen', sq: 'Përfunduar' },
  'rep.photo': { en: 'Photo', de: 'Foto', sq: 'Foto' },
  'field.amount_eur': { en: 'Amount (EUR)', de: 'Betrag (EUR)', sq: 'Shuma (EUR)' },
  'field.address': { en: 'Address', de: 'Adresse', sq: 'Adresa' },
  'field.member': { en: 'Member', de: 'Mitglied', sq: 'Anëtari' },
  'field.date': { en: 'Date', de: 'Datum', sq: 'Data' },
  'field.amount': { en: 'Amount', de: 'Betrag', sq: 'Shuma' },
  'ph.zip_short': { en: 'ZIP', de: 'PLZ', sq: 'Kodi postar' },
  'ph.city_short': { en: 'City', de: 'Ort', sq: 'Qyteti' },
  'ph.street_short': { en: 'Street', de: 'Strasse', sq: 'Rruga' },
  'ph.country_hint': { en: 'Country (e.g. Switzerland)', de: 'Land (z. B. Schweiz)', sq: 'Shteti (p.sh. Zvicër)' },
  'ph.phone_short': { en: '+41...', de: '+41...', sq: '+41...' },

  // --- ADMIN: NAVIGATION ---
  'admin.group.management': { en: 'Management', de: 'Verwaltung', sq: 'Menaxhimi' },
  'admin.group.finance': { en: 'Finance', de: 'Finanzen', sq: 'Financat' },
  'admin.group.content': { en: 'Content', de: 'Inhalte', sq: 'Përmbajtja' },
  'admin.group.system': { en: 'System', de: 'System', sq: 'Sistemi' },
  'admin.tab.news': { en: 'News feed', de: 'Nachrichten', sq: 'Lajmet' },
  'admin.tab.data': { en: 'Data centre', de: 'Datenverwaltung', sq: 'Qendra e të Dhënave' },
  'admin.tab.communication': { en: 'Communication', de: 'Kommunikation', sq: 'Komunikimi' },
  'admin.brand.label': { en: 'Administration', de: 'Verwaltung', sq: 'Administrimi' },

  // --- ADMIN: MITGLIEDER ---
  'admin.members.legacy_email': { en: 'Please replace the temporary email address (@koretini.legacy) before saving.', de: 'Bitte ersetzen Sie die temporäre E-Mail-Adresse (@koretini.legacy), bevor Sie speichern.', sq: 'Ju lutem përditësoni email-in e përkohshëm (@koretini.legacy) para se të ruani.' },
  'admin.members.updated': { en: 'Member updated.', de: 'Mitglied erfolgreich aktualisiert.', sq: 'Anëtari u përditësua.' },
  'admin.members.created': { en: 'Member created.', de: 'Mitglied erfolgreich erfasst.', sq: 'Anëtari u regjistrua.' },
  'admin.members.save_failed': { en: 'Could not save: {reason}', de: 'Fehler beim Speichern: {reason}', sq: 'Ruajtja dështoi: {reason}' },
  'admin.members.remove_title': { en: 'Remove member?', de: 'Mitglied entfernen?', sq: 'Largo anëtarin?' },
  'admin.members.remove_text': { en: '{name} will be set to inactive and will no longer appear in the list or publicly. Data and invoices are kept. You can restore the member via the "Inactive" filter.', de: '{name} wird auf inaktiv gesetzt und erscheint weder in der Liste noch öffentlich. Daten und Rechnungen bleiben erhalten. Über den Filter „Inaktiv“ lässt sich das rückgängig machen.', sq: '{name} do të vendoset joaktiv dhe nuk do të shfaqet më në listë e as publikisht. Të dhënat dhe faturat ruhen. Mund ta rikthesh përmes filtrit "Joaktiv".' },
  'admin.members.remove': { en: 'Remove', de: 'Entfernen', sq: 'Largo' },
  'admin.members.reactivate': { en: 'Reactivate', de: 'Reaktivieren', sq: 'Riaktivizo' },
  'admin.members.reactivate_title': { en: 'Reactivate member', de: 'Mitglied reaktivieren', sq: 'Riaktivizo anëtarin' },
  'admin.members.remove_action': { en: 'Remove member', de: 'Mitglied entfernen', sq: 'Largo anëtarin' },
  'admin.members.invalid_email': { en: 'Invalid email', de: 'Ungültige E-Mail', sq: 'Email i pavlefshëm' },
  'admin.members.invalid_email_title': { en: 'Invalid or temporary email address', de: 'Ungültige oder temporäre E-Mail-Adresse', sq: 'Email i pavlefshëm ose i përkohshëm' },
  'admin.members.legacy_hint': { en: 'Invalid email (legacy)', de: 'Ungültige E-Mail (Altbestand)', sq: 'Email i pavlefshëm (Legacy)' },
  'admin.members.count': { en: 'Members', de: 'Mitglieder', sq: 'Anëtarë' },
  'admin.members.register': { en: 'Member register', de: 'Mitgliederregister', sq: 'Regjistri i Anëtarëve' },
  'admin.members.phone_primary': { en: 'Primary phone', de: 'Telefon (primär)', sq: 'Telefoni Primar' },
  'admin.members.phone_secondary': { en: 'Secondary phone', de: 'Telefon (zweit)', sq: 'Telefoni Sekondar' },
  'admin.members.street_no': { en: 'Street & no.', de: 'Strasse & Nr.', sq: 'Rruga & Nr.' },
  'admin.members.invoice_delivery': { en: 'Invoice delivery', de: 'Rechnungsversand', sq: 'Mënyra e dërgimit të faturës' },
  'admin.members.billing_group': { en: 'Billing group', de: 'Beitragsgruppe', sq: 'Grupi i faturimit' },
  'admin.members.billing.standard': { en: 'Standard (diaspora)', de: 'Standard (Diaspora)', sq: 'STANDARD (Diaspora)' },
  'admin.members.billing.kosovo': { en: 'Kosovo (resident)', de: 'Kosovo (vor Ort)', sq: 'KOSOVO (Resident)' },
  'admin.members.billing.reduced': { en: 'Reduced (special)', de: 'Ermässigt (Sonderfall)', sq: 'REDUCED (Special)' },
  'admin.members.custom_fee': { en: 'Individual fee (override)', de: 'Individueller Beitrag (Übersteuerung)', sq: 'Anëtarësia e personalizuar (Override)' },
  'admin.members.family_id': { en: 'Family ID', de: 'Familien-ID', sq: 'Familje ID' },
  'admin.members.family_id_prompt': { en: 'Enter the family ID:', de: 'Familien-ID eingeben:', sq: 'Shëno ID-në e familjes:' },
  'admin.members.role': { en: 'Role', de: 'Rolle', sq: 'Roli i përdoruesit' },
  'admin.members.notes_board': { en: 'Internal notes (board only)', de: 'Interne Notizen (nur Vorstand)', sq: 'Shënime Interne (Board Only)' },
  'admin.members.notes_ph': { en: 'Additional notes about this member...', de: 'Zusätzliche Angaben zum Mitglied...', sq: 'Shëno detaje shtesë për anëtarin...' },
  'admin.members.neighborhood': { en: 'Neighborhood', de: 'Nachbarschaft', sq: 'Lagjja' },
  'admin.members.payment_history': { en: 'Payment history', de: 'Zahlungsverlauf', sq: 'Historiku i pagesave' },
  'admin.members.no_payments': { en: 'No payments recorded yet.', de: 'Noch keine Zahlungen erfasst.', sq: 'Ende asnjë pagesë të regjistruar.' },
  'admin.members.back_to_list': { en: 'Back to list', de: 'Zurück zur Liste', sq: 'Mbrapa te Lista' },

  // --- ADMIN: RECHNUNG ERSTELLEN ---
  'admin.invoice.new': { en: 'Create new invoice', de: 'Neue Rechnung erstellen', sq: 'Krijo Faturë të Re' },
  'admin.invoice.create': { en: 'Create invoice', de: 'Rechnung erstellen', sq: 'Krijo Faturën' },
  'admin.invoice.due': { en: 'Due date', de: 'Fälligkeit', sq: 'Afati' },
  'admin.invoice.created': { en: 'Invoice created.', de: 'Rechnung erstellt.', sq: 'Fatura u krijua me sukses.' },
  'admin.invoice.failed': { en: 'Could not create invoice: {reason}', de: 'Rechnung konnte nicht erstellt werden: {reason}', sq: 'Gabim gjatë krijimit të faturës: {reason}' },

  // --- ADMIN: EVENTS ---
  'admin.events.title': { en: 'Event management', de: 'Veranstaltungen verwalten', sq: 'Menaxhimi i Ngjarjeve' },
  'admin.events.add': { en: 'Add event', de: 'Veranstaltung hinzufügen', sq: 'Shto Event' },
  'admin.events.none': { en: 'No events recorded.', de: 'Keine Veranstaltungen erfasst.', sq: 'Asnjë event i regjistruar.' },
  'admin.events.saved': { en: 'Event saved.', de: 'Veranstaltung gespeichert.', sq: 'Event u ruajt me sukses.' },
  'admin.events.details': { en: 'Event details', de: 'Details der Veranstaltung', sq: 'Detajet e Eventit' },
  'admin.events.save': { en: 'Save event', de: 'Veranstaltung speichern', sq: 'Ruaj Eventin' },
  'admin.events.registration': { en: 'Registration', de: 'Anmeldung', sq: 'Regjistrimi' },
  'admin.events.registrations': { en: 'Registration management', de: 'Anmeldungen verwalten', sq: 'Menaxhimi i Regjistrimeve' },
  'admin.events.no_registrations': { en: 'No registrations for this event yet.', de: 'Noch keine Anmeldungen für diese Veranstaltung.', sq: 'Asnjë regjistrim ende për këtë event.' },
  'admin.events.export_csv': { en: 'Download list (CSV)', de: 'Liste herunterladen (CSV)', sq: 'Shkarko Listën (CSV)' },
  'admin.events.nothing_to_export': { en: 'No registrations to export.', de: 'Keine Anmeldungen zum Exportieren.', sq: 'Nuk ka regjistrime për të eksportuar.' },
  'admin.events.past': { en: 'Past', de: 'Vergangen', sq: 'Kaluar' },
  'admin.events.current': { en: 'Current', de: 'Aktuell', sq: 'Aktual' },
  'admin.events.upcoming': { en: 'Upcoming', de: 'Bevorstehend', sq: 'Në të ardhmen' },
  'admin.events.approve': { en: 'Approve', de: 'Annehmen', sq: 'Mirato' },
  'admin.events.reject': { en: 'Reject', de: 'Ablehnen', sq: 'Refuzo' },

  // --- ADMIN: NACHRICHTEN ---
  'admin.news.title': { en: 'News editor', de: 'Nachrichten bearbeiten', sq: 'News Feed Editor' },
  'admin.news.add': { en: 'Add article', de: 'Beitrag hinzufügen', sq: 'Shto Lajm' },
  'admin.news.none': { en: 'No articles published.', de: 'Keine Beiträge veröffentlicht.', sq: 'Nuk ka lajme të publikuara.' },
  'admin.news.saved': { en: 'Article saved.', de: 'Beitrag gespeichert.', sq: 'Lajmi u ruajt me sukses.' },
  'admin.news.details': { en: 'Article details', de: 'Details des Beitrags', sq: 'Detajet e Lajmit' },
  'admin.news.save': { en: 'Save article', de: 'Beitrag speichern', sq: 'Ruaj Lajmin' },
  'admin.news.schedule': { en: 'Schedule publication', de: 'Veröffentlichung planen', sq: 'Termino Publikimin' },
  'admin.news.date_scheduled': { en: 'Date / scheduled', de: 'Datum / geplant', sq: 'Data / Programuar' },
  'admin.news.body_first': { en: 'Text (first paragraph)', de: 'Text (erster Abschnitt)', sq: 'Përmbajtja (Paragrafi i parë)' },
  'admin.news.location': { en: 'Location', de: 'Ort', sq: 'Lokacioni' },

  // --- ADMIN: VEROEFFENTLICHUNG ---
  'admin.publish.status': { en: 'Publication status', de: 'Veröffentlichungsstatus', sq: 'Statusi i Publikimit' },
  'admin.publish.draft': { en: 'Draft', de: 'Entwurf', sq: 'Draft' },
  'admin.publish.published': { en: 'Published', de: 'Veröffentlicht', sq: 'Publikuar' },
  'admin.publish.archived': { en: 'Archived', de: 'Archiviert', sq: 'Arkivuar' },

  // --- ADMIN: DATENQUALITAET ---
  'admin.dq.avg': { en: 'Average quality', de: 'Durchschnittliche Qualität', sq: 'Cilësia Mesatare' },
  'admin.dq.action_needed': { en: 'Action needed', de: 'Handlungsbedarf', sq: 'Veprim i kërkuar' },
  'admin.dq.monitor': { en: 'Data monitoring', de: 'Datenüberwachung', sq: 'Monitorimi i të dhënave' },
  'admin.dq.missing': { en: 'Missing', de: 'Fehlt', sq: 'Mungon' },
  'admin.dq.quality': { en: 'Quality', de: 'Qualität', sq: 'Cilësia' },
  'admin.dq.complete': { en: 'Complete ✓', de: 'Vollständig ✓', sq: 'E kompletuar ✓' },

  // --- ADMIN: NACHBARSCHAFTEN ---
  'admin.nb.local_unit': { en: 'Local unit', de: 'Lokale Einheit', sq: 'Njësi Lokale' },
  'admin.nb.participation': { en: 'Participation', de: 'Beteiligung', sq: 'Pjesëmarrja' },
  'admin.nb.paid_suffix': { en: 'paid', de: 'bezahlt', sq: 'të paguara' },
  'admin.nb.manager': { en: 'Neighborhood manager', de: 'Verantwortliche Person', sq: 'Përgjegjësi i Njësisë' },
  'admin.nb.manager_badge': { en: 'Neighborhood manager', de: 'Nachbarschafts-Verantwortliche', sq: 'Lagje-Manager' },

  // --- ALLGEMEINE FELDER ---
  'field.title': { en: 'Title', de: 'Titel', sq: 'Titulli' },
  'field.description': { en: 'Description', de: 'Beschreibung', sq: 'Përshkrimi' },
  'field.image_url': { en: 'Image URL', de: 'Bild-URL', sq: 'URL e Fotos' },
  'field.role': { en: 'Role', de: 'Rolle', sq: 'Roli' },
  'field.info': { en: 'Info', de: 'Info', sq: 'Info' },
  'cat.culture': { en: 'Culture', de: 'Kultur', sq: 'Kulturë' },
  'cat.education': { en: 'Education', de: 'Bildung', sq: 'Arsim' },
  'cat.health': { en: 'Health', de: 'Gesundheit', sq: 'Shëndetësi' },
  'cat.social': { en: 'Social', de: 'Soziales', sq: 'Sociale' },
  'cat.sport': { en: 'Sport', de: 'Sport', sq: 'Sport' },
  'cat.diaspora': { en: 'Diaspora', de: 'Diaspora', sq: 'Diasporë' },
  'cat.local': { en: 'Local', de: 'Lokal', sq: 'Lokale' },
  'cat.project': { en: 'Project', de: 'Projekt', sq: 'Projekt' },
  'admin.delete_permanent': { en: 'This cannot be undone.', de: 'Dieser Schritt lässt sich nicht rückgängig machen.', sq: 'Ky veprim nuk mund të kthehet.' },
  'admin.deleted': { en: 'Deleted.', de: 'Gelöscht.', sq: 'U fshi me sukses.' },
  'admin.save_failed': { en: 'Saving failed: {reason}', de: 'Speichern fehlgeschlagen: {reason}', sq: 'Dështoi ruajtja: {reason}' },
  'admin.nb.contributions': { en: 'Contributions {year}', de: 'Beiträge {year}', sq: 'Kontributet {year}' },

  // --- ROLLEN ---
  'role.member': { en: 'Member', de: 'Mitglied', sq: 'Anëtar' },
  'role.board': { en: 'Board', de: 'Vorstand', sq: 'Kryesia' },
  'role.nb_manager': { en: 'Neighborhood manager', de: 'Nachbarschafts-Verantwortliche', sq: 'Përgjegjës lagjeje' },
  'role.representative': { en: 'Local representative', de: 'Vertretung vor Ort', sq: 'Përfaqësues lokal' },
  'role.admin': { en: 'Administration', de: 'Administration', sq: 'Administrata' },
  'role.super_admin': { en: 'Platform owner', de: 'Plattform-Betreiber', sq: 'Pronar i platformës' },
  'role.guest': { en: 'Guest', de: 'Gast', sq: 'Mysafir' },

  // --- RECHNUNGS-E-MAIL ---
  'mail.invoice.subject': { en: 'Invoice {number} — {association}', de: 'Rechnung {number} — {association}', sq: 'Faturë {number} — {association}' },
  'mail.invoice.heading': { en: 'Invoice', de: 'Rechnung', sq: 'Faturë' },
  'mail.invoice.greeting': { en: 'Hello', de: 'Guten Tag', sq: 'Përshëndetje' },
  'mail.invoice.intro': { en: 'Below you will find the details of your membership payment:', de: 'Nachfolgend finden Sie die Angaben zu Ihrem Mitgliederbeitrag:', sq: 'Ju lutem gjeni më poshtë detajet për pagesën e anëtarësisë:' },
  'mail.invoice.number': { en: 'Invoice no.', de: 'Rechnungsnummer', sq: 'Nr. i faturës' },
  'mail.invoice.due': { en: 'Due date', de: 'Zahlbar bis', sq: 'Afati i pagesës' },
  'mail.invoice.due_immediate': { en: 'Immediately', de: 'Sofort', sq: 'Menjëherë' },
  'mail.invoice.thanks': { en: 'Thank you for supporting our community.', de: 'Danke, dass Sie unsere Gemeinschaft unterstützen.', sq: 'Faleminderit që mbështesni komunitetin tonë.' },
  'mail.pay.bank_qr': { en: 'Payment details (bank transfer / Swiss QR)', de: 'Zahlungsinformationen (Banküberweisung / Swiss QR)', sq: 'Informacionet e pagesës (transfer bankar / Swiss QR)' },
  'mail.pay.sepa': { en: 'Payment details (SEPA transfer)', de: 'Zahlungsinformationen (SEPA-Überweisung)', sq: 'Informacionet e pagesës (transfer SEPA)' },
  'mail.pay.paypal': { en: 'Payment details (PayPal)', de: 'Zahlungsinformationen (PayPal)', sq: 'Informacionet e pagesës (PayPal)' },
  'mail.pay.generic': { en: 'Payment details', de: 'Zahlungsinformationen', sq: 'Informacionet e pagesës' },
  'mail.pay.paypal_intro': { en: 'Please send the amount to our PayPal address:', de: 'Bitte senden Sie den Betrag an unsere PayPal-Adresse:', sq: 'Ju lutem dërgoni shumën në adresën tonë PayPal:' },
  'mail.pay.paypal_reference': { en: 'Please always state your invoice number as the reference:', de: 'Geben Sie als Verwendungszweck unbedingt Ihre Rechnungsnummer an:', sq: 'Si referencë ju lutem shënoni patjetër numrin e faturës:' },
  'mail.pay.twint_title': { en: 'Payment via TWINT', de: 'Zahlung per TWINT', sq: 'Pagesa me TWINT' },
  'mail.pay.twint_intro': { en: 'You can also send the amount conveniently via TWINT to this number:', de: 'Sie können den Betrag auch bequem per TWINT an folgende Nummer senden:', sq: 'Shumën mund ta dërgoni edhe me TWINT në këtë numër:' },
  'mail.pay.twint_button': { en: 'Pay with TWINT now', de: 'Jetzt mit TWINT bezahlen', sq: 'Paguaj tani me TWINT' },
  'mail.sent_to': { en: 'Invoice sent to {email}', de: 'Rechnung an {email} gesendet', sq: 'Fatura u dërgua te {email}' },
  'mail.send_failed': { en: 'Could not send the email.', de: 'Die E-Mail konnte nicht gesendet werden.', sq: 'E-maili nuk mund të dërgohej.' },
  'mail.no_address': { en: 'No valid email address for this recipient.', de: 'Keine gültige E-Mail-Adresse für diesen Empfänger.', sq: 'Nuk ka adresë e-maili të vlefshme për këtë marrës.' },
  'mail.bulk.title': { en: 'Send invoices by email', de: 'Rechnungen per E-Mail senden', sq: 'Dërgo faturat me e-mail' },
  'mail.bulk.text': { en: 'Send invoices to {count} recipients by email?', de: 'Rechnungen an {count} Empfänger per E-Mail senden?', sq: 'Të dërgohen faturat te {count} marrës me e-mail?' },
  'mail.bulk.confirm': { en: 'Send all', de: 'Alle senden', sq: 'Dërgo të gjitha' },
  'field.not_specified': { en: 'Not specified', de: 'Nicht angegeben', sq: 'E paspecifikuar' },
  'field.not_configured': { en: 'Not configured', de: 'Nicht konfiguriert', sq: 'E pakonfiguruar' },
  'field.bank': { en: 'Bank', de: 'Bank', sq: 'Banka' },
  'field.account_holder': { en: 'Account holder', de: 'Kontoinhaber', sq: 'Mbajtësi i llogarisë' },
  'field.iban': { en: 'IBAN', de: 'IBAN', sq: 'IBAN' },
  'field.bic': { en: 'BIC', de: 'BIC', sq: 'BIC' },
  'field.reference': { en: 'Reference', de: 'Referenz', sq: 'Referenca' },
  'field.purpose': { en: 'Reference / purpose', de: 'Verwendungszweck', sq: 'Qëllimi i pagesës' },
  'field.recipient': { en: 'Recipient', de: 'Empfänger', sq: 'Marrësi' },
  'field.currency': { en: 'Currency', de: 'Währung', sq: 'Valuta' },
  'field.due_date': { en: 'Due date', de: 'Fälligkeitsdatum', sq: 'Data e afatit' },
  'field.name': { en: 'Name', de: 'Name', sq: 'Emri' },

  // --- ADMIN: FINANZEN ---
  'admin.finance.budget': { en: 'Budget', de: 'Budget', sq: 'Buxheti' },
  'admin.finance.budget_saved': { en: 'Budget for {year} saved.', de: 'Budget für {year} gespeichert.', sq: 'Buxheti për {year} u ruajt.' },
  'admin.finance.save_failed': { en: 'Could not save.', de: 'Fehler beim Speichern.', sq: 'Ruajtja dështoi.' },
  'admin.finance.settings_saved': { en: 'Settings saved.', de: 'Einstellungen gespeichert.', sq: 'Cilësimet u ruajtën.' },
  'admin.finance.settings_failed': { en: 'Could not save the settings.', de: 'Einstellungen konnten nicht gespeichert werden.', sq: 'Cilësimet nuk u ruajtën.' },
  'admin.finance.reminder_failed': { en: 'Could not send the reminder.', de: 'Mahnung konnte nicht gesendet werden.', sq: 'Përkujtesa nuk u dërgua.' },
  'admin.finance.invoice_failed': { en: 'Could not create the invoice.', de: 'Rechnung konnte nicht erstellt werden.', sq: 'Fatura nuk u krijua.' },
  'admin.finance.delete_invoice': { en: 'Delete invoice', de: 'Rechnung löschen', sq: 'Fshij faturën' },
  'admin.finance.marked_paid': { en: 'Marked as paid.', de: 'Als bezahlt markiert.', sq: 'U shënua si e paguar.' },
  'admin.finance.fill_amount_desc': { en: 'Please enter an amount and a description.', de: 'Bitte Betrag und Beschreibung ausfüllen.', sq: 'Ju lutem plotësoni shumën dhe përshkrimin.' },
  'admin.finance.select_member': { en: 'Please select a member.', de: 'Bitte ein Mitglied auswählen.', sq: 'Ju lutem zgjidhni një anëtar.' },
  'admin.finance.enter_recipient': { en: 'Please enter a recipient name.', de: 'Bitte einen Empfängernamen eingeben.', sq: 'Ju lutem shënoni emrin e marrësit.' },
  'admin.finance.select_one_member': { en: 'Please select at least one member.', de: 'Bitte mindestens ein Mitglied auswählen.', sq: 'Ju lutem zgjidhni së paku një anëtar.' },
  'admin.finance.recent_activity': { en: 'Recent activity', de: 'Letzte Bewegungen', sq: 'Aktiviteti i fundit' },
  'admin.finance.to_print': { en: 'To print', de: 'Zu drucken', sq: 'Për të shtypur' },
  'admin.finance.method_via': { en: 'Method / via', de: 'Weg / Versand', sq: 'Mënyra / Dërgimi' },
  'admin.finance.post': { en: 'Post', de: 'Post', sq: 'Postë' },
  'admin.finance.no_overdue': { en: 'No overdue payments', de: 'Keine überfälligen Zahlungen', sq: 'Asnjë pagesë e vonuar' },
  'admin.finance.no_overdue_text': { en: 'There are currently no open invoices that need a reminder.', de: 'Aktuell gibt es keine offenen Rechnungen, die angemahnt werden müssen.', sq: 'Aktualisht nuk ka fatura të hapura që kërkojnë përkujtesë.' },
  'admin.finance.send_reminder': { en: 'Send reminder', de: 'Mahnung senden', sq: 'Dërgo përkujtesë' },
  'admin.finance.income': { en: 'Income', de: 'Einnahmen (Ertrag)', sq: 'Të hyrat' },
  'admin.finance.expenses': { en: 'Expenses', de: 'Ausgaben (Aufwand)', sq: 'Shpenzimet' },
  'admin.finance.total_income': { en: 'Total income', de: 'Total Einnahmen', sq: 'Totali i të hyrave' },
  'admin.finance.total_expenses': { en: 'Total expenses', de: 'Total Ausgaben', sq: 'Totali i shpenzimeve' },
  'admin.finance.budget_result': { en: 'Budgeted result', de: 'Budgetiertes Ergebnis', sq: 'Rezultati i buxhetuar' },
  'admin.finance.bank_qr_settings': { en: 'Bank & QR settings', de: 'Bank- und QR-Einstellungen', sq: 'Cilësimet e bankës & QR' },
  'admin.finance.iban_diff_title': { en: 'Difference between IBAN and QR-IBAN:', de: 'Unterschied IBAN und QR-IBAN:', sq: 'Dallimi mes IBAN dhe QR-IBAN:' },
  'admin.finance.iban_standard': { en: 'Standard IBAN:', de: 'Standard-IBAN:', sq: 'IBAN standard:' },
  'admin.finance.iban_standard_desc': { en: 'Used for ordinary transfers without a 27-digit reference.', de: 'Wird für normale Überweisungen ohne 27-stellige Referenz genutzt.', sq: 'Përdoret për transfere normale pa referencë 27-shifrore.' },
  'admin.finance.qr_iban': { en: 'QR-IBAN:', de: 'QR-IBAN:', sq: 'QR-IBAN:' },
  'admin.finance.qr_iban_desc': { en: 'A separate number issued by your bank (IID 30000–31999).', de: 'Eigene Nummer Ihrer Bank (IID 30000–31999).', sq: 'Numër i veçantë i bankës suaj (IID 30000–31999).' },
  'admin.finance.mandatory': { en: 'Mandatory', de: 'Zwingend erforderlich', sq: 'E detyrueshme' },
  'admin.finance.iban_standard_label': { en: 'Standard IBAN (for ordinary payments)', de: 'Standard-IBAN (für normale Zahlungen)', sq: 'IBAN standard (për pagesa normale)' },
  'admin.finance.qr_iban_label': { en: 'QR-IBAN (required for the 27-digit reference)', de: 'QR-IBAN (zwingend für die 27-stellige Referenz)', sq: 'QR-IBAN (e detyrueshme për referencën 27-shifrore)' },
  'admin.finance.recommended': { en: 'Recommended', de: 'Empfohlen', sq: 'E rekomanduar' },
  'admin.finance.bank_name': { en: 'Bank name', de: 'Name der Bank', sq: 'Emri i bankës' },
  'admin.finance.bank_address': { en: 'Address of the bank / account holder', de: 'Adresse der Bank bzw. des Kontoinhabers', sq: 'Adresa e bankës / mbajtësit të llogarisë' },
  'admin.finance.twint_settings': { en: 'TWINT settings (Switzerland)', de: 'TWINT-Einstellungen (Schweiz)', sq: 'Cilësimet TWINT (Zvicër)' },
  'admin.finance.twint_number': { en: 'TWINT number (mobile)', de: 'TWINT-Nummer (Mobile)', sq: 'Numri TWINT (mobil)' },
  'admin.finance.twint_url': { en: 'TWINT PayLink / URL (optional)', de: 'TWINT PayLink / URL (optional)', sq: 'TWINT PayLink / URL (opsionale)' },
  'admin.finance.paypal_settings': { en: 'PayPal settings (international)', de: 'PayPal-Einstellungen (international)', sq: 'Cilësimet PayPal (ndërkombëtare)' },
  'admin.finance.paypal_email': { en: 'PayPal email', de: 'PayPal-E-Mail', sq: 'E-maili i PayPal' },
  'admin.finance.paypal_client': { en: 'PayPal client ID (API)', de: 'PayPal Client ID (API)', sq: 'PayPal Client ID (API)' },
  'admin.finance.paypal_secret': { en: 'PayPal secret (API)', de: 'PayPal Secret (API)', sq: 'PayPal Secret (API)' },
  'admin.finance.single_invoice': { en: 'Single invoice', de: 'Einzelrechnung', sq: 'Faturë e vetme' },
  'admin.finance.bulk_invoice': { en: 'Bulk invoices', de: 'Sammelrechnung', sq: 'Faturim i grumbulluar' },
  'admin.finance.external': { en: 'External', de: 'Extern', sq: 'I jashtëm' },
  'admin.finance.choose_member': { en: 'Choose member', de: 'Mitglied auswählen', sq: 'Zgjidh anëtarin' },
  'admin.finance.please_choose': { en: 'Please choose...', de: 'Bitte wählen...', sq: 'Ju lutem zgjidhni...' },
  'admin.finance.create_invoices': { en: 'Create invoice(s)', de: 'Rechnung(en) erstellen', sq: 'Krijo faturë(a)' },
  'admin.finance.twint_payment': { en: 'TWINT payment', de: 'TWINT-Zahlung', sq: 'Pagesa me TWINT' },
  'admin.finance.twint_pay_intro': { en: 'Pay conveniently via TWINT to this number:', de: 'Zahlen Sie bequem per TWINT an folgende Nummer:', sq: 'Paguani lehtë me TWINT në këtë numër:' },
  'admin.finance.girocode': { en: 'GiroCode (SEPA)', de: 'GiroCode (SEPA)', sq: 'GiroCode (SEPA)' },
  'admin.finance.paypal_payment': { en: 'PayPal payment', de: 'PayPal-Zahlung', sq: 'Pagesa me PayPal' },
  'admin.finance.bill_to': { en: 'Invoice to:', de: 'Rechnung an:', sq: 'Faturuar për:' },
  'admin.finance.total_due': { en: 'Total due', de: 'Gesamtbetrag', sq: 'Totali për pagesë' },
  'admin.finance.thanks': { en: 'Thank you for your contribution.', de: 'Danke für Ihren Beitrag.', sq: 'Faleminderit për kontributin tuaj.' },
  'admin.finance.download_pdf': { en: 'Download PDF', de: 'PDF herunterladen', sq: 'Shkarko PDF' },
  'admin.finance.bulk_created': { en: '{count} invoices created.', de: '{count} Rechnungen erstellt.', sq: '{count} fatura u krijuan.' },
  'admin.finance.bulk_created_skipped': { en: '{count} invoices created, {skipped} skipped (already invoiced for {year}).', de: '{count} Rechnungen erstellt, {skipped} übersprungen (bereits für {year} verrechnet).', sq: '{count} fatura u krijuan, {skipped} u anashkaluan (tashmë të faturuara për {year}).' },
  'admin.finance.qr_iban_hint': { en: 'Mandatory if you want to use the automated 27-digit reference for reconciliation.', de: 'Zwingend, wenn Sie die automatische 27-stellige Referenz für den Abgleich nutzen wollen.', sq: 'E detyrueshme nëse doni të përdorni referencën automatike 27-shifrore për barazim.' },
  'admin.finance.qr_iban_empty': { en: 'If left empty, the standard IBAN is used for the QR code (without the 27-digit reference).', de: 'Bleibt das Feld leer, wird die Standard-IBAN für den QR-Code verwendet (ohne 27-stellige Referenz).', sq: 'Nëse mbetet bosh, përdoret IBAN-i standard për kodin QR (pa referencë 27-shifrore).' },
  'admin.finance.preview_invoice': { en: 'Invoice preview #{number}', de: 'Rechnungsvorschau #{number}', sq: 'Parapamje e faturës #{number}' },
  'admin.finance.paypal_pay_intro': { en: 'Please send the amount to our PayPal address and state your invoice number as the reference.', de: 'Bitte senden Sie den Betrag an unsere PayPal-Adresse und geben Sie Ihre Rechnungsnummer als Verwendungszweck an.', sq: 'Ju lutem dërgoni shumën në adresën tonë PayPal dhe shënoni numrin e faturës si referencë.' },

  // --- ADMIN: VORSTAND & PROTOKOLLE ---
  'ed.bold': { en: 'Bold', de: 'Fett', sq: 'Trash' },
  'ed.italic': { en: 'Italic', de: 'Kursiv', sq: 'Pjerrët' },
  'ed.bullets': { en: 'Bullet list', de: 'Aufzählung', sq: 'Listë me pika' },
  'minutes.default_title': { en: 'Board meeting', de: 'Vorstandssitzung', sq: 'Mbledhja e Kryesisë' },
  'minutes.saved': { en: 'Minutes saved.', de: 'Protokoll gespeichert.', sq: 'Protokolli u ruajt.' },
  'minutes.delete_title': { en: 'Delete minutes', de: 'Protokoll löschen', sq: 'Fshij Protokollin' },
  'minutes.title_ph': { en: 'Title of the meeting', de: 'Titel der Sitzung', sq: 'Titulli i Mbledhjes' },
  'minutes.tab': { en: 'Minutes & meetings', de: 'Protokolle & Sitzungen', sq: 'Protokolle & Mbledhje' },
  'minutes.new': { en: 'New minutes', de: 'Neues Protokoll', sq: 'Protokoll i Ri' },
  'minutes.archive': { en: 'Archive', de: 'Archiv', sq: 'Arkiva' },
  'minutes.preview_pdf': { en: 'Preview / PDF', de: 'Vorschau / PDF', sq: 'Parapamje / PDF' },
  'minutes.preview': { en: 'Minutes preview', de: 'Protokollvorschau', sq: 'Parapamje e protokollit' },
  'minutes.download_pdf': { en: 'Download / print PDF', de: 'PDF herunterladen / drucken', sq: 'Shkarko / shtyp PDF' },
  'minutes.share': { en: 'Share', de: 'Teilen', sq: 'Ndaj' },
  'minutes.copied': { en: 'Summary copied to the clipboard.', de: 'Zusammenfassung in die Zwischenablage kopiert.', sq: 'Përmbledhja u kopjua në clipboard!' },
  'minutes.heading': { en: 'Minutes', de: 'Protokoll', sq: 'Protokoll' },
  'minutes.pick_or_create': { en: 'Choose a set of minutes or create a new one.', de: 'Wählen Sie ein Protokoll oder legen Sie ein neues an.', sq: 'Zgjidhni një protokoll ose krijoni të ri.' },
  'minutes.agenda': { en: 'Agenda', de: 'Traktanden', sq: 'Rendi i Ditës' },
  'minutes.agenda_discussions': { en: 'Agenda & discussion', de: 'Traktanden & Diskussion', sq: 'Rendi i Ditës & Diskutimet' },
  'minutes.agenda_item_ph': { en: 'Agenda item...', de: 'Traktandum...', sq: 'Pika e rendit të ditës...' },
  'minutes.add_item': { en: 'Add item', de: 'Traktandum hinzufügen', sq: 'Shto pikë' },
  'minutes.topic_details': { en: 'Details of the items', de: 'Details zu den Traktanden', sq: 'Detajet e Temave' },
  'minutes.topic_hint': { en: 'Add agenda items to write the details.', de: 'Fügen Sie Traktanden hinzu, um Details zu erfassen.', sq: 'Shtoni pika në rendin e ditës për të shkruar detajet.' },
  'minutes.add_attendee': { en: 'Add attendee...', de: 'Teilnehmende hinzufügen...', sq: 'Shto Pjesëmarrës...' },
  'minutes.guests_others': { en: 'Guests & others', de: 'Gäste & Weitere', sq: 'Mysafirë & Të Tjerë' },
  'minutes.present': { en: 'Present', de: 'Anwesend', sq: 'Të pranishëm' },
  'minutes.chair': { en: 'Chair', de: 'Vorsitz', sq: 'Kryesuesi' },
  'minutes.secretary': { en: 'Minute taker', de: 'Protokollführung', sq: 'Protokollisti' },
  'minutes.fill_title_owner': { en: 'Please enter a title and the person responsible.', de: 'Bitte Titel und verantwortliche Person angeben.', sq: 'Ju lutem plotësoni titullin dhe personin përgjegjës.' },
  'board.members_title': { en: 'Board members', de: 'Vorstandsmitglieder', sq: 'Anëtarët e Kryesisë' },
  'board.sync_roles': { en: 'Synchronise roles', de: 'Rollen abgleichen', sq: 'Sinkronizo Rolet' },
  'board.add_member': { en: 'Add new member', de: 'Mitglied hinzufügen', sq: 'Shto Anëtar të Ri' },
  'board.choose_member': { en: 'Choose member...', de: 'Mitglied wählen...', sq: 'Zgjidh Anëtarin...' },
  'board.function_ph': { en: 'Function (e.g. president)', de: 'Funktion (z. B. Präsidium)', sq: 'Funksioni (psh. Kryetar)' },
  'board.quote_ph': { en: 'Quote or description...', de: 'Zitat oder Beschreibung...', sq: 'Citat ose Përshkrim...' },
  'board.save_member': { en: 'Save member', de: 'Mitglied speichern', sq: 'Ruaj Anëtarin' },
  'board.already_in_list': { en: 'This person is already in the list.', de: 'Diese Person steht bereits in der Liste.', sq: 'Ky person është tashmë në listë.' },
  'board.member_added': { en: 'Member added and role updated.', de: 'Mitglied hinzugefügt und Rolle aktualisiert.', sq: 'Anëtari u shtua dhe u përditësua roli.' },
  'board.member_removed': { en: 'Member removed, role reset to Member.', de: 'Mitglied entfernt, Rolle auf Mitglied zurückgesetzt.', sq: 'Anëtari u fshi dhe roli u kthye në Member.' },
  'board.delete_member': { en: 'Remove board member', de: 'Vorstandsmitglied entfernen', sq: 'Fshij Anëtarin' },
  'board.function': { en: 'Function', de: 'Funktion', sq: 'Funksioni' },
  'task.actions': { en: 'Actions / tasks', de: 'Massnahmen / Aufgaben', sq: 'Veprime / Detyra' },
  'task.create': { en: 'Create task', de: 'Aufgabe erstellen', sq: 'Krijo Detyrë' },
  'task.created': { en: 'Task created.', de: 'Aufgabe erstellt.', sq: 'Detyra u krijua me sukses!' },
  'task.none_for_item': { en: 'No task created for this item.', de: 'Für dieses Traktandum wurde keine Aufgabe erstellt.', sq: 'Asnjë detyrë e krijuar për këtë pikë.' },
  'task.title': { en: 'Task title', de: 'Titel der Aufgabe', sq: 'Titulli i Detyrës' },
  'task.owner': { en: 'Person responsible', de: 'Verantwortliche Person', sq: 'Personi Përgjegjës' },
  'task.due': { en: 'Due date', de: 'Fällig bis', sq: 'Afati' },
  'task.priority': { en: 'Priority', de: 'Priorität', sq: 'Prioriteti' },
  'prio.low': { en: 'Low', de: 'Niedrig', sq: 'E ulët' },
  'prio.medium': { en: 'Medium', de: 'Mittel', sq: 'Mesatare' },
  'prio.high': { en: 'High', de: 'Hoch', sq: 'E lartë' },
  'common.create': { en: 'Create', de: 'Erstellen', sq: 'Krijo' },
  'field.responsible': { en: 'Responsible', de: 'Verantwortlich', sq: 'Përgjegjësi' },

  // --- ADMIN: BUCHHALTUNG ---
  'acc.fill_all': { en: 'Please fill in all fields.', de: 'Bitte alle Felder ausfüllen.', sq: 'Ju lutem plotësoni të gjitha fushat.' },
  'acc.year_closed': { en: 'This financial year is already closed.', de: 'Das Geschäftsjahr ist bereits abgeschlossen.', sq: 'Viti financiar është tashmë i mbyllur.' },
  'acc.booked': { en: 'Entry booked.', de: 'Buchung erfolgreich.', sq: 'Regjistrimi u krye.' },
  'acc.book_failed': { en: 'Could not post the entry.', de: 'Fehler beim Buchen.', sq: 'Regjistrimi dështoi.' },
  'acc.pick_accounts': { en: 'Please choose the accounts and the outgoing amount.', de: 'Bitte Konten und Ausgangsbetrag wählen.', sq: 'Ju lutem zgjidhni llogaritë dhe shumën dalëse.' },
  'acc.transfer_ok': { en: 'Transfer posted.', de: 'Übertrag verbucht.', sq: 'Transferi u regjistrua.' },
  'acc.transfer_failed': { en: 'Could not post the transfer.', de: 'Fehler beim Übertrag.', sq: 'Transferi dështoi.' },
  'acc.book_payments': { en: 'Post payments', de: 'Zahlungen verbuchen', sq: 'Regjistro pagesat' },
  'acc.precheck_failed': { en: 'Pre-check failed, closing aborted.', de: 'Vorprüfung fehlgeschlagen, Abschluss abgebrochen.', sq: 'Kontrolli paraprak dështoi, mbyllja u ndërpre.' },
  'acc.use_of_funds': { en: 'Use of funds', de: 'Mittelverwendung', sq: 'Përdorimi i mjeteve' },
  'acc.source_of_funds': { en: 'Source of funds', de: 'Mittelherkunft', sq: 'Burimi i mjeteve' },
  'acc.result': { en: 'Result for the year', de: 'Unternehmenserfolg', sq: 'Rezultati i vitit' },
  'acc.journal': { en: 'Journal', de: 'Buchungsjournal', sq: 'Ditari i regjistrimeve' },
  'acc.journal_desc': { en: 'Chronological list of all transactions.', de: 'Chronologische Liste aller Buchungen.', sq: 'Listë kronologjike e të gjitha transaksioneve.' },
  'acc.transfer': { en: 'Account transfer', de: 'Kontoübertrag', sq: 'Transfer llogarie' },
  'acc.transfer_title': { en: 'Account transfer / exchange', de: 'Kontoübertrag / Wechsel', sq: 'Transfer llogarie / këmbim' },
  'acc.transfer_desc': { en: 'Transfer of liquid funds (e.g. bank to cash, or a currency exchange).', de: 'Übertrag liquider Mittel (z. B. Bank zu Kasse oder Währungswechsel).', sq: 'Transfer i mjeteve likuide (p.sh. bankë në arkë ose këmbim valutor).' },
  'acc.system': { en: 'System', de: 'System', sq: 'Sistemi' },
  'acc.balance': { en: 'Balance', de: 'Saldo', sq: 'Saldo' },
  'acc.csv_export': { en: 'CSV export', de: 'CSV-Export', sq: 'Eksport CSV' },
  'acc.print': { en: 'Print', de: 'Drucken', sq: 'Shtyp' },
  'acc.entry_text': { en: 'Entry text', de: 'Buchungstext', sq: 'Teksti i regjistrimit' },
  'acc.contra_account': { en: 'Contra account', de: 'Gegenkonto', sq: 'Llogaria kundërshtuese' },
  'acc.purpose_ph': { en: 'Purpose of the entry...', de: 'Zweck der Buchung...', sq: 'Qëllimi i regjistrimit...' },
  'acc.from_credit': { en: 'From (credit)', de: 'Von (Haben)', sq: 'Nga (Kredi)' },
  'acc.to_debit': { en: 'To (debit)', de: 'Nach (Soll)', sq: 'Në (Debi)' },
  'acc.amount_out': { en: 'Amount out', de: 'Betrag Ausgang', sq: 'Shuma dalëse' },
  'acc.amount_out_hint': { en: 'Amount in the source currency', de: 'Betrag in der Ausgangswährung', sq: 'Shuma në valutën burimore' },
  'acc.amount_in': { en: 'Amount in', de: 'Betrag Eingang', sq: 'Shuma hyrëse' },
  'acc.amount_in_hint': { en: 'Amount in the target currency', de: 'Betrag in der Zielwährung', sq: 'Shuma në valutën e destinacionit' },
  'acc.do_transfer': { en: 'Post transfer', de: 'Umbuchen', sq: 'Transfero' },
  'acc.processing': { en: 'Processing data...', de: 'Daten werden verarbeitet...', sq: 'Duke përpunuar të dhënat...' },

  // --- ADMIN: AUSGABEN ---
  'exp.scanned': { en: 'Receipt read successfully.', de: 'Beleg erfolgreich analysiert.', sq: 'Fatura u lexua me sukses.' },
  'exp.scan_failed': { en: 'Could not read the receipt. Please enter the details manually.', de: 'Beleg konnte nicht gelesen werden. Bitte manuell eingeben.', sq: 'Fatura nuk u lexua. Ju lutem shënoni manualisht.' },
  'exp.fill_vendor_amount': { en: 'Please enter the vendor and the amount.', de: 'Bitte Lieferant und Betrag angeben.', sq: 'Ju lutem shënoni furnitorin dhe shumën.' },
  'exp.saved': { en: 'Expense saved.', de: 'Ausgabe gespeichert.', sq: 'Shpenzimi u ruajt.' },
  'exp.save_failed': { en: 'Could not save the expense.', de: 'Fehler beim Speichern.', sq: 'Ruajtja dështoi.' },
  'exp.fx_needed': { en: 'Currency conversion required', de: 'Währungsumrechnung erforderlich', sq: 'Nevojitet konvertim valutor' },
  'exp.invalid_amount': { en: 'Invalid amount.', de: 'Ungültiger Betrag.', sq: 'Shumë e pavlefshme.' },
  'exp.book_title': { en: 'Post expense', de: 'Ausgabe verbuchen', sq: 'Regjistro shpenzimin' },
  'exp.booked': { en: 'Posted successfully.', de: 'Erfolgreich verbucht.', sq: 'U regjistrua me sukses.' },
  'exp.book_failed': { en: 'Could not post the expense.', de: 'Fehler bei der Buchung.', sq: 'Regjistrimi dështoi.' },
  'exp.abroad': { en: 'Abroad', de: 'Ausland', sq: 'Jashtë vendit' },
  'exp.none': { en: 'No expenses found.', de: 'Keine Ausgaben gefunden.', sq: 'Nuk u gjetën shpenzime.' },
  'exp.receipt_preview': { en: 'Receipt preview', de: 'Belegvorschau', sq: 'Parapamje e faturës' },
  'exp.vendor_ph': { en: 'e.g. Market Prishtina', de: 'z. B. Market Prishtina', sq: 'p.sh. Market Prishtina' },
  'exp.purpose_ph': { en: 'Purpose of the expense', de: 'Zweck der Ausgabe', sq: 'Qëllimi i shpenzimit' },

  // --- ADMIN: AUFGABEN ---
  'task.to_todo': { en: 'Move to to-do', de: 'Nach „Offen“ verschieben', sq: 'Zhvendos te "Për të bërë"' },
  'task.to_progress': { en: 'Move to in progress', de: 'Nach „In Arbeit“ verschieben', sq: 'Zhvendos te "Në punë"' },
  'task.to_done': { en: 'Move to done', de: 'Nach „Erledigt“ verschieben', sq: 'Zhvendos te "Përfunduar"' },
  'task.assign': { en: 'Assign task', de: 'Aufgabe zuweisen', sq: 'Cakto detyrën' },
  'task.assign_prompt': { en: 'Name of the person responsible:', de: 'Name der verantwortlichen Person:', sq: 'Emri i personit përgjegjës:' },
  'task.delete': { en: 'Delete task', de: 'Aufgabe löschen', sq: 'Fshij detyrën' },
  'task.new_ph': { en: 'New task...', de: 'Neue Aufgabe...', sq: 'Detyrë e re...' },
  'common.add': { en: 'Add', de: 'Hinzufügen', sq: 'Shto' },

  // --- ADMIN: STATISTIK ---
  'stats.base_vs_payers': { en: 'Member base compared with active payers.', de: 'Mitgliederbestand im Vergleich zu den zahlenden Mitgliedern.', sq: 'Baza e anëtarëve krahasuar me paguesit aktivë.' },
  'stats.monthly': { en: 'Collections over the course of the year.', de: 'Einnahmen im Jahresverlauf.', sq: 'Të hyrat gjatë vitit.' },
  'stats.late': { en: 'Late', de: 'Verspätet', sq: 'Me vonesë' },
  'stats.unpaid': { en: 'Unpaid', de: 'Unbezahlt', sq: 'E papaguar' },
  'stats.last_payment': { en: 'Last payment', de: 'Letzte Zahlung', sq: 'Pagesa e fundit' },
  'stats.no_members': { en: 'No members match this filter.', de: 'Keine Mitglieder entsprechen diesem Filter.', sq: 'Asnjë anëtar nuk i përgjigjet këtij filtri.' },
  'stats.health': { en: 'Health', de: 'Zustand', sq: 'Gjendja' },

  // --- ADMIN: EINSTELLUNGEN ---
  'set.saved': { en: 'System settings updated.', de: 'Systemeinstellungen aktualisiert.', sq: 'Cilësimet e sistemit u përditësuan.' },
  'set.save_failed': { en: 'Could not update the settings.', de: 'Einstellungen konnten nicht aktualisiert werden.', sq: 'Cilësimet nuk u përditësuan.' },
  'set.title': { en: 'System control', de: 'Systemsteuerung', sq: 'Kontrolli i sistemit' },
  'set.subtitle': { en: 'Platform-wide configuration and feature switches.', de: 'Plattformweite Konfiguration und Funktionsschalter.', sq: 'Konfigurimi i platformës dhe çelësat e funksioneve.' },
  'set.status': { en: 'System status', de: 'Systemstatus', sq: 'Statusi i sistemit' },
  'set.access': { en: 'Access & security', de: 'Zugang & Sicherheit', sq: 'Qasja & siguria' },
  'set.maintenance': { en: 'Maintenance mode', de: 'Wartungsmodus', sq: 'Modaliteti i mirëmbajtjes' },
  'set.allow_registration': { en: 'Allow registration', de: 'Registrierung erlauben', sq: 'Lejo regjistrimin' },
  'set.modules': { en: 'Visible modules', de: 'Sichtbare Module', sq: 'Modulet e dukshme' },
  'set.mod_live': { en: 'Koretini Live (3D)', de: 'Koretini Live (3D)', sq: 'Koretini Live (3D)' },
  'set.mod_events': { en: 'Events calendar', de: 'Veranstaltungskalender', sq: 'Kalendari i ngjarjeve' },
  'set.mod_news': { en: 'News feed', de: 'Nachrichten', sq: 'Lajmet' },
  'set.fees': { en: 'Fee structure (billing groups)', de: 'Beitragsstruktur (Beitragsgruppen)', sq: 'Struktura e anëtarësisë (grupet e faturimit)' },
  'set.fee_standard_desc': { en: 'Diaspora & Switzerland', de: 'Diaspora & Schweiz', sq: 'Diaspora & Zvicra' },
  'set.fee_resident': { en: 'Resident (XK)', de: 'Vor Ort (XK)', sq: 'Rezident (XK)' },
  'set.fee_resident_desc': { en: 'Members living in Kosovo', de: 'Mitglieder in Kosovo', sq: 'Anëtarët në Kosovë' },
  'set.fee_reduced': { en: 'Reduced', de: 'Ermässigt', sq: 'E reduktuar' },
  'set.fee_reduced_desc': { en: 'Students / special cases', de: 'Studierende / Sonderfälle', sq: 'Studentë / raste të veçanta' },
  'set.communication': { en: 'Communication', de: 'Kommunikation', sq: 'Komunikimi' },
  'set.reply_to': { en: 'Reply-to address of the system', de: 'Antwortadresse des Systems', sq: 'Adresa e përgjigjes së sistemit' },
  'set.reply_to_hint': { en: 'Used for automated invoice notifications.', de: 'Wird für automatische Rechnungsmeldungen verwendet.', sq: 'Përdoret për njoftimet automatike të faturave.' },
  'set.smtp': { en: 'SMTP configuration', de: 'SMTP-Konfiguration', sq: 'Konfigurimi SMTP' },

  // --- ADMIN: DATENVERWALTUNG ---
  'data.title': { en: 'Data centre', de: 'Datenverwaltung', sq: 'Qendra e të dhënave' },
  'data.subtitle': { en: 'Import and export system data as CSV.', de: 'Systemdaten per CSV importieren und exportieren.', sq: 'Importo dhe eksporto të dhënat e sistemit si CSV.' },
  'data.migrating': { en: 'Migrating members...', de: 'Mitglieder werden migriert...', sq: 'Duke migruar anëtarët...' },
  'data.csv_only': { en: 'Supports .csv files', de: 'Unterstützt .csv-Dateien', sq: 'Mbështet skedarë .csv' },
  'data.import': { en: 'Import', de: 'Importieren', sq: 'Importo' },
  'data.export': { en: 'Export', de: 'Exportieren', sq: 'Eksporto' },
  'data.nb_desc': { en: 'Manage neighborhoods and local groups.', de: 'Nachbarschaften und lokale Gruppen verwalten.', sq: 'Menaxho lagjet dhe grupet lokale.' },
  'data.payments': { en: 'Payments', de: 'Zahlungen', sq: 'Pagesat' },
  'data.payments_desc': { en: 'Import bank CSVs. Members are matched by email or reference.', de: 'Bank-CSVs importieren. Die Zuordnung erfolgt über E-Mail oder Referenz.', sq: 'Importo CSV bankare. Përputhja bëhet me e-mail ose referencë.' },
  'data.golive': { en: 'Go-live preparation', de: 'Vorbereitung für den Live-Betrieb', sq: 'Përgatitja për nisje' },
  'data.golive_desc': { en: 'Deletes test data (members, payments, journal) and keeps the admin account.', de: 'Löscht Testdaten (Mitglieder, Zahlungen, Journal) und behält das Administratorkonto.', sq: 'Fshin të dhënat e testit (anëtarë, pagesa, ditar) dhe ruan llogarinë e administratorit.' },
  'data.golive_button': { en: 'Reset operational data', de: 'Betriebsdaten zurücksetzen', sq: 'Rivendos të dhënat operative' },
  'data.golive_title': { en: 'Go-live preparation', de: 'Vorbereitung für den Live-Betrieb', sq: 'Përgatitja për nisje' },
  'data.golive_text': { en: 'This deletes all test members, payments, expenses and accounting data.\n\nYour admin account is kept.\n\nType GO-LIVE to confirm.', de: 'Damit werden alle Testmitglieder, Zahlungen, Ausgaben und Buchhaltungsdaten gelöscht.\n\nIhr Administratorkonto bleibt erhalten.\n\nGeben Sie GO-LIVE ein, um zu bestätigen.', sq: 'Kjo fshin të gjithë anëtarët e testit, pagesat, shpenzimet dhe të dhënat kontabël.\n\nLlogaria juaj e administratorit ruhet.\n\nShkruani GO-LIVE për të konfirmuar.' },
  'data.golive_done': { en: 'Ready for go-live. Operational data cleared.', de: 'Bereit für den Live-Betrieb. Betriebsdaten gelöscht.', sq: 'Gati për nisje. Të dhënat operative u fshinë.' },
  'data.factory': { en: 'Factory reset', de: 'Werkseinstellungen', sq: 'Rivendosje në gjendje fabrike' },
  'data.factory_desc': { en: 'Irreversible. Deletes everything, including neighborhoods and settings.', de: 'Nicht umkehrbar. Löscht alles, auch Nachbarschaften und Einstellungen.', sq: 'E pakthyeshme. Fshin gjithçka, përfshirë lagjet dhe cilësimet.' },
  'data.factory_button': { en: 'Delete all data', de: 'Alle Daten löschen', sq: 'Fshij të gjitha të dhënat' },
  'data.factory_title': { en: 'Warning: factory reset', de: 'Achtung: Werkseinstellungen', sq: 'Kujdes: rivendosje në fabrikë' },
  'data.factory_text': { en: 'This deletes all data, potentially including your own admin settings. Type DELETE-ALL to confirm.', de: 'Damit werden alle Daten gelöscht, unter Umständen auch Ihre eigenen Administratoreinstellungen. Geben Sie DELETE-ALL ein, um zu bestätigen.', sq: 'Kjo fshin të gjitha të dhënat, ndoshta edhe cilësimet tuaja të administratorit. Shkruani DELETE-ALL për të konfirmuar.' },
  'data.factory_done': { en: 'System reset complete.', de: 'Zurücksetzen abgeschlossen.', sq: 'Rivendosja e sistemit përfundoi.' },
  'data.log': { en: 'System log', de: 'Systemprotokoll', sq: 'Regjistri i sistemit' },
  'data.log_waiting': { en: 'Waiting for actions...', de: 'Warte auf Aktionen...', sq: 'Duke pritur veprime...' },

  // --- ADMIN: KOMMUNIKATION ---
  'comm.polls': { en: 'Polls', de: 'Umfragen', sq: 'Sondazhet' },
  'comm.newsletter': { en: 'Newsletter', de: 'Newsletter', sq: 'Buletini' },
  'comm.poll_created': { en: 'Poll created.', de: 'Umfrage erstellt.', sq: 'Sondazhi u krijua.' },
  'comm.poll_delete': { en: 'Delete poll', de: 'Umfrage löschen', sq: 'Fshij sondazhin' },
  'comm.newsletter_title': { en: 'Send newsletter', de: 'Newsletter senden', sq: 'Dërgo buletinin' },
  'comm.newsletter_confirm': { en: 'This sends an email to all members. Are you sure?', de: 'Damit geht eine E-Mail an alle Mitglieder. Sind Sie sicher?', sq: 'Kjo dërgon një e-mail te të gjithë anëtarët. A jeni i sigurt?' },
  'comm.newsletter_queued': { en: 'Newsletter queued (test message sent to the administrator).', de: 'Newsletter eingereiht (Testnachricht an die Administration gesendet).', sq: 'Buletini u vendos në radhë (mesazhi i testit u dërgua te administratori).' },
  'comm.failed': { en: 'Failed.', de: 'Fehlgeschlagen.', sq: 'Dështoi.' },
  'comm.note_title': { en: 'Add internal note', de: 'Interne Notiz hinzufügen', sq: 'Shto shënim të brendshëm' },
  'comm.note_text': { en: 'This note will be visible to the member.', de: 'Diese Notiz ist für das Mitglied sichtbar.', sq: 'Ky shënim do të jetë i dukshëm për anëtarin.' },
  'comm.admin_response': { en: 'Response from the board', de: 'Antwort des Vorstands', sq: 'Përgjigje e kryesisë' },
  'comm.no_inquiries': { en: 'No enquiries found.', de: 'Keine Anfragen gefunden.', sq: 'Nuk u gjetën kërkesa.' },
  'comm.new_poll': { en: 'Create new poll', de: 'Neue Umfrage erstellen', sq: 'Krijo sondazh të ri' },
  'comm.question_ph': { en: 'Question (e.g. should we renovate the school?)', de: 'Frage (z. B. Sollen wir die Schule renovieren?)', sq: 'Pyetja (p.sh. A duhet ta rinovojmë shkollën?)' },
  'comm.launch_poll': { en: 'Start poll', de: 'Umfrage starten', sq: 'Nis sondazhin' },
  'comm.subject': { en: 'Subject', de: 'Betreff', sq: 'Subjekti' },
  'comm.message_html': { en: 'Message (HTML supported)', de: 'Nachricht (HTML möglich)', sq: 'Mesazhi (HTML i mbështetur)' },
  'comm.send_all': { en: 'Send to all members', de: 'An alle Mitglieder senden', sq: 'Dërgo te të gjithë anëtarët' },
  'inq.open': { en: 'Open', de: 'Offen', sq: 'E hapur' },
  'inq.in_progress': { en: 'In progress', de: 'In Arbeit', sq: 'Në punë' },
  'inq.done': { en: 'Done', de: 'Erledigt', sq: 'Përfunduar' },
  'inq.rejected': { en: 'Rejected', de: 'Abgelehnt', sq: 'E refuzuar' },

  // --- ADMIN: TESTLABOR ---
  'lab.unlocked': { en: 'Test lab unlocked.', de: 'Testlabor entsperrt.', sq: 'Laboratori i testeve u zhbllokua.' },
  'lab.invalid_password': { en: 'Wrong password.', de: 'Falsches Passwort.', sq: 'Fjalëkalim i gabuar.' },
  'lab.restricted': { en: 'Restricted area', de: 'Geschützter Bereich', sq: 'Zonë e kufizuar' },
  'lab.password_ph': { en: 'Enter the master password...', de: 'Master-Passwort eingeben...', sq: 'Shkruani fjalëkalimin kryesor...' },
  'lab.unlock': { en: 'Unlock', de: 'Entsperren', sq: 'Zhblloko' },
  'lab.title': { en: 'Test lab', de: 'Testlabor', sq: 'Laboratori i testeve' },
  'lab.subtitle': { en: 'Run system diagnostics and health checks, and view the state of the automated tests.', de: 'Systemdiagnose und Zustandsprüfungen ausführen und den Stand der automatisierten Tests einsehen.', sq: 'Kryeni diagnostikim të sistemit dhe kontrolle, dhe shikoni gjendjen e testeve të automatizuara.' },
  'lab.health': { en: 'Live health check', de: 'Zustandsprüfung im Betrieb', sq: 'Kontroll i gjendjes në kohë reale' },
  'lab.health_desc': { en: 'Queries the database to measure read latency and connection health.', de: 'Fragt die Datenbank ab, um Leselatenz und Verbindungsqualität zu messen.', sq: 'Pyet bazën e të dhënave për të matur vonesën e leximit dhe gjendjen e lidhjes.' },
  'lab.integrity': { en: 'Data integrity', de: 'Datenintegrität', sq: 'Integriteti i të dhënave' },
  'lab.integrity_desc': { en: 'Scans the tables for orphaned records, missing references and anomalies.', de: 'Durchsucht die Tabellen nach verwaisten Datensätzen, fehlenden Verweisen und Auffälligkeiten.', sq: 'Skanon tabelat për të dhëna të orfanuara, referenca që mungojnë dhe anomali.' },
  'lab.ready': { en: 'Ready to run', de: 'Bereit zum Start', sq: 'Gati për nisje' },
  'lab.suites': { en: 'Automated test suites (CI/CD)', de: 'Automatisierte Testsuiten (CI/CD)', sq: 'Suita testesh të automatizuara (CI/CD)' },
  'lab.configured': { en: 'Configured & ready', de: 'Eingerichtet & bereit', sq: 'E konfiguruar & gati' },
  'lab.status': { en: 'Status:', de: 'Status:', sq: 'Statusi:' },
  'lab.location': { en: 'Location:', de: 'Ablageort:', sq: 'Vendndodhja:' },
  'lab.frameworks': { en: 'Frameworks:', de: 'Frameworks:', sq: 'Frameworks:' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  /**
   * Loest einen aus der Datenbank stammenden Wert auf, der entweder ein
   * einfacher String oder ein Objekt { de, en, sq } sein kann. Fallback-Kette:
   * gewaehlte Sprache -> Deutsch -> Albanisch -> Englisch -> erster Eintrag.
   */
  loc: (value: any) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('koretini_lang');
    if (saved === 'en' || saved === 'de' || saved === 'sq') return saved;
    return 'sq'; 
  });

  useEffect(() => {
    localStorage.setItem('koretini_lang', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[key]?.[language] || key;
    if (params) {
        Object.keys(params).forEach(param => {
            text = text.replace(`{${param}}`, String(params[param]));
        });
    }
    return text;
  };

  const loc = (value: any): string => {
    if (value === null || value === undefined) return '';
    if (typeof value === 'string') return value;
    if (typeof value !== 'object') return String(value);
    const candidates = [value[language], value.de, value.sq, value.en];
    const hit = candidates.find((v) => typeof v === 'string' && v.trim() !== '');
    if (hit) return hit;
    const first = Object.values(value).find((v) => typeof v === 'string' && (v as string).trim() !== '');
    return (first as string) || '';
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, loc }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useTranslation must be used within a LanguageProvider');
  return context;
};
